import {HEROES,CHARACTERS,WAVES,SLOTS,SAVE_KEY,CAPACITY,MAX_TIER,stats,keyOf,superCost} from './data.mjs';
import {fresh,buy,buyFromCodex,mergePreview,merge,moveHero,dismiss,refund,start,pause,retry,nextWave,step,serialize,restore,canEdit} from './engine.mjs';
import {portrait,heroArt,icon} from './art.mjs';import {makeRenderer} from './render.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let g;try{g=restore(localStorage.getItem(SAVE_KEY));}catch{g=fresh();}
let selection=[g.units[0].id],mode='normal',moving=false,filter='all',highlight='',renderer,lastPhase=g.phase,last=0,hudElapsed=0,toastTimer,confirmAction,audio;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
$$('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
const selectedUnits=()=>selection.map(id=>g.units.find(u=>u.id===id)).filter(Boolean);
function save(){try{localStorage.setItem(SAVE_KEY,serialize(g));$('#save-status').textContent='용사단과 도감을 이 기기에 저장해요';}catch{$('#save-status').textContent='저장이 제한되어 이번 화면에서만 플레이할 수 있어요';}}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');if($('#codex-dialog').open)$('#codex-status').textContent=message;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),4000);}
function sound(type){if(g.muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const notes=type==='merge'?[392,523,659,784]:type==='win'?[392,494,587,784]:type==='lost'?[392,330,262]:[659,880];notes.forEach((hz,i)=>{const o=audio.createOscillator(),a=audio.createGain(),t=audio.currentTime+i*.08;o.type='triangle';o.frequency.setValueAtTime(hz,t);a.gain.setValueAtTime(.0001,t);a.gain.exponentialRampToValueAtTime(.04,t+.015);a.gain.exponentialRampToValueAtTime(.0001,t+.17);o.connect(a);a.connect(audio.destination);o.start(t);o.stop(t+.18);});}catch{}}
function action(r,tone='coin'){if(r.ok){save();sound(tone);}render();toast(r.message);return r;}
function select(id){moving=false;if(selection.includes(id))selection=selection.filter(n=>n!==id);else selection=selection.length===2?[id]:[...selection,id];render();}
function focusKey(){const e=document.activeElement;if(e?.id)return '#'+e.id;for(const k of ['unit','buy','mode','slot','gembuy','filter'])if(e?.dataset?.[k]!==undefined)return `[data-${k}="${e.dataset[k]}"]`;return null;}
function render(){const focused=document.activeElement,focus=focusKey();selection=selection.filter(id=>g.units.some(u=>u.id===id));const chosen=selectedUnits(),a=chosen[0],edit=canEdit(g),preview=mergePreview(g,selection,mode),affordable=preview.ok&&g.coins>=preview.cost;document.body.dataset.phase=g.phase;document.body.dataset.wave=g.wave;document.body.dataset.mode=mode;
$('#coins').textContent=g.coins;$('#gems').textContent=g.gems;$('#collection-count').textContent=g.discovered.length+' / 14';$('#stage-count').textContent=`라운드 ${g.wave} / 20`;
const offset=g.wave>10?10:0;$('#wave-track').innerHTML=WAVES.slice(offset,offset+10).map((w,i)=>{const n=i+1+offset;return `<li class="${n===g.wave?'current':n<g.wave?'done':''}" ${n===g.wave?'aria-current="step"':''} aria-label="${n}단계">${n<g.wave?icon('check'):n}</li>`;}).join('');
$('#wave-badge').textContent=String(g.wave).padStart(2,'0');$('#wave-title').textContent=WAVES[g.wave-1].name;$('#phase-label').textContent={prep:'준비 시간 · 용사단을 꾸며요',battle:'전투 중 · 자동으로 싸워요',paused:'잠깐 쉬는 중',reward:'경기장 방어 성공!',lost:'다시 도전할 수 있어요',won:'20번의 모험을 모두 완료했어요'}[g.phase];$('#battle-tip').textContent=WAVES[g.wave-1].tip;
$('#hero-shop').innerHTML=Object.entries(HEROES).map(([type,h])=>{const s=CHARACTERS[type+'-1'];return `<article class="hero-card ${type}"><div class="portrait">${heroArt(type)}</div><div><h3>${s.name}<span class="role">${h.name} · 1단계</span></h3><div class="mini-stats"><span>♥ ${s.hp}</span><span>⚔ ${s.power}</span></div></div><button class="buy-hero" data-buy="${type}" aria-label="${s.name} 구매 ${h.cost} 코인" ${!edit||g.coins<h.cost||g.units.length>=CAPACITY?'disabled':''}><span>${!edit?'전투 중':g.units.length>=CAPACITY?'용사단 가득':g.coins<h.cost?'코인 부족':'코인으로 구매'}</span><b>${icon('coin')}${h.cost}</b></button></article>`;}).join('');
$('#slot-controls').innerHTML=SLOTS.map((s,i)=>{const u=g.units.find(u=>u.slot===i);return `<button class="slot-control ${u&&selection.includes(u.id)?'active':''}" data-slot="${i}" style="left:${s.x/10}%;top:${(s.y-80)/450*100}%" aria-label="${s.row} ${u?stats(u).name:'빈자리'}" ${!edit?'disabled':''}>${i+1}</button>`;}).join('');
$('#pause-overlay').hidden=g.phase!=='paused';const actions={prep:['play','전투 시작'],battle:['pause','잠깐 멈춤'],paused:['play','이어하기'],reward:['arrow','다음 준비'],lost:['reset','다시 준비'],won:['spark','모험 완료']},[ic,txt]=actions[g.phase];$('#start').innerHTML=icon(ic)+`<span>${txt}</span>`;$('#speed').textContent=g.speed+'×';$('#speed').setAttribute('aria-label',`전투 속도 ${g.speed===1?2:1}배로 변경`);$('#sound').innerHTML=icon(g.muted?'mute':'sound');$('#sound').setAttribute('aria-label',g.muted?'소리 켜기':'소리 끄기');$('#sound').setAttribute('aria-pressed',String(!g.muted));
$$('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));$('#mode-description').textContent=mode==='normal'?'같은 공격 타입 + 같은 별 단계의 친구 둘을 합쳐요.':'근거리 + 원거리도 가능! 첫 번째 친구의 타입으로 한 단계 성장해요.';
$('#merge-preview').innerHTML=chosen.map((u,i)=>`<div class="merge-avatar filled">${portrait(u)}<small>${i===0?'①':'②'} ${stats(u).name}</small></div>`).join('<span class="mix-operator">+</span>')+(chosen.length===0?'<div class="merge-avatar">?</div><span class="mix-operator">+</span><div class="merge-avatar">?</div>':chosen.length===1?'<span class="mix-operator">+</span><div class="merge-avatar">?</div>':'')+`<span class="mix-operator">→</span><div class="merge-avatar result">${preview.ok?portrait(preview.character)+`<small>${preview.character.tier}단계</small>`:icon('spark')}</div>`;
$('#merge-info').innerHTML=preview.ok?`<b>${stats(a).name} → ${preview.character.name}</b><p>체력 ${stats(a).hp.toLocaleString()} → ${preview.character.hp.toLocaleString()}<br>공격력 ${stats(a).power} → ${preview.character.power}</p>`:`<b>${chosen.length===2?preview.message:'어떤 용사가 탄생할까요?'}</b><p>${chosen.length===2?'선택한 용사를 한 번 더 누르면 해제돼요.':mode==='super'?'주인공을 먼저, 합체 친구를 나중에 골라요.':'우리 용사단에서 같은 용사 두 명을 골라요.'}</p>`;
$('#merge').disabled=!edit||!preview.ok||!affordable;$('#merge').innerHTML=icon('spark')+`<span>${!edit?'전투가 끝나면 합체할 수 있어요':preview.ok?(affordable?(mode==='super'?`슈퍼 합체 · ${preview.cost} 코인`:'반짝! 무료 합체'):`코인 ${preview.cost-g.coins}개 부족해요`):'용사 두 명을 골라 주세요'}</span>`;$('#merge-cost-note').textContent=mode==='normal'?'일반 합체는 무료 · 두 명이 한 명이 돼요':preview.ok?`두 명이 ${preview.character.name} 한 명으로 합체해요 · ${preview.cost} 코인 사용`:'주인공 ★1~6 비용: 80 · 160 · 280 · 440 · 650 · 900 코인';
const matches=a&&a.tier<MAX_TIER?g.units.filter(u=>u.id!==a.id&&u.type===a.type&&u.tier===a.tier):[];$('#team-count').textContent=`${g.units.length} / ${CAPACITY}명`;$('#match-count').textContent=mode==='normal'&&matches.length?`같은 용사 ${matches.length}명 있어요!`:'';
$('#team').innerHTML=g.units.map(u=>{const s=stats(u),n=selection.indexOf(u.id);return `<button class="unit-card ${u.type} ${n>=0?'selected':''} ${mode==='normal'&&selection.length===1&&matches.includes(u)?'match':''}" data-unit="${u.id}" data-key="${s.key}" aria-pressed="${n>=0}" aria-label="${s.name} ${HEROES[u.type].name} ${s.tier}단계, 체력 ${s.hp}, 공격력 ${s.power}, ${u.slot===null?'대기석':SLOTS[u.slot].row}"><span class="type-pill ${u.type}">${HEROES[u.type].name}</span>${portrait(u)}<b>${s.name}</b><span class="tier-stars">${'★'.repeat(u.tier)}</span><span class="unit-place">${u.slot===null?'대기석':SLOTS[u.slot].row}</span>${n>=0?`<span class="selection-number">${n+1}${mode==='super'&&n===0?' 주인공':''}</span>`:''}</button>`;}).join('')+Array.from({length:Math.max(0,6-g.units.length)},()=>'<div class="empty-unit" aria-hidden="true">+</div>').join('');
$('#selected-detail').innerHTML=a?`<h3><span class="type-pill ${a.type}">${HEROES[a.type].name}</span> ${stats(a).name} · ${a.tier}단계 ${chosen.length===2?'(첫 번째 용사)':''}</h3><div class="detail-stats"><span>체력 <b>${stats(a).hp.toLocaleString()}</b></span><span>공격력 <b>${stats(a).power}</b></span></div><p class="fixed-role">${a.type==='melee'?'가까이 다가가서 공격해요.':stats(a).weapon==='missile'?'제자리에서 미사일을 발사해요.':'제자리에서 장난감 총을 쏴요.'} 자리를 옮겨도 그대로예요.</p><div class="detail-actions"><button id="move" ${!edit?'disabled':''}>${moving?'자리 선택 중':a.slot===null?'전장에 배치':'자리 옮기기'}</button><button id="bench" ${!edit||a.slot===null?'disabled':''}>대기석으로</button><button id="see-character">도감 보기</button><button class="dismiss" id="dismiss" ${!edit||g.units.length===1?'disabled':''}>돌려보내고 ${refund(a)} 코인 받기</button></div>`:'<p>용사를 누르면 체력과 공격력도 볼 수 있어요.</p>';
$('#tutorial').hidden=g.discovered.some(k=>CHARACTERS[k].tier>=2)||!edit;if($('#codex-dialog').open)renderCodex();updateHUD();if(focus&&!focused.isConnected){const e=$(focus);if(e&&!e.disabled)e.focus({preventScroll:true});}}
function updateHUD(){$('#coins').textContent=g.coins;$('#gems').textContent=g.gems;$('#crystal').value=g.crystal;$('#crystal-label').textContent=g.crystal;$('#map-status').textContent=g.phase==='prep'?(moving?'이동할 자리를 눌러 주세요. 친구끼리 교환도 가능!':`전장 ${g.units.filter(u=>u.slot!==null).length}명 · 대기 ${g.units.filter(u=>u.slot===null).length}명`):g.phase==='battle'?`물리친 적 ${g.run.kills} / ${WAVES[g.wave-1].types.length} · 코인 +${g.run.earned}`:g.phase==='paused'?'천천히 생각해도 괜찮아요':'우리 용사단, 수고했어요!';}
$('#hero-shop').addEventListener('click',e=>{const b=e.target.closest('[data-buy]');if(!b)return;const r=buy(g,b.dataset.buy);if(r.ok){selection=[r.id];moving=false;}action(r);});
$('#team').addEventListener('click',e=>{const b=e.target.closest('[data-unit]');if(b)select(Number(b.dataset.unit));});
$$('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;moving=false;render();});$('#clear').onclick=()=>{selection=[];moving=false;render();};
$('#merge').onclick=()=>{const r=merge(g,selection,mode);if(r.ok){selection=[r.id];moving=false;$('#merge-area').classList.remove('merged');void $('#merge-area').offsetWidth;$('#merge-area').classList.add('merged');}action(r,'merge');};
$('#selected-detail').addEventListener('click',e=>{const a=selectedUnits()[0];if(!a)return;if(e.target.closest('#move')){selection=[a.id];moving=!moving;render();if(moving){$('#battle-area').scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});toast('전장에서 이동할 자리를 눌러 주세요.');}}else if(e.target.closest('#bench'))action(moveHero(g,a.id,null));else if(e.target.closest('#see-character'))openCodex(keyOf(a));else if(e.target.closest('#dismiss'))confirm('용사를 돌려보낼까요?',`${stats(a).name}이 떠나고 ${refund(a)}코인을 돌려받아요. 도감 기록은 그대로 남아요.`,()=>{const r=dismiss(g,a.id);selection=[];action(r);});});
$('#slot-controls').addEventListener('click',e=>{const b=e.target.closest('[data-slot]');if(!b||!canEdit(g))return;const slot=Number(b.dataset.slot),u=g.units.find(u=>u.slot===slot),a=selectedUnits()[0];if(moving&&a){moving=false;action(moveHero(g,a.id,slot));}else if(u){selection=[u.id];render();}else if(a)action(moveHero(g,a.id,slot));});
function mainAction(){if(g.phase==='prep'){moving=false;action(start(g));if(innerWidth<821)$('#battle-area').scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});}else if(['battle','paused'].includes(g.phase)){pause(g);save();render();}else if(g.phase==='reward'){nextWave(g);save();render();}else if(g.phase==='lost'){retry(g);save();render();}else showResult();}
$('#start').onclick=mainAction;$('#speed').onclick=()=>{g.speed=g.speed===1?2:1;save();render();};$('#sound').onclick=()=>{g.muted=!g.muted;save();render();sound('coin');};
function openDialog(id){if(g.phase==='battle'){pause(g);render();}$(id).showModal();}
function openCodex(key=''){highlight=key;filter=key?CHARACTERS[key].type:'all';renderCodex();$('#codex-status').textContent='';openDialog('#codex-dialog');if(key)$(`[data-codex="${key}"]`)?.scrollIntoView({block:'nearest'});}
function renderCodex(){const f=focusKey(),active=document.activeElement;$('#codex-progress').textContent=g.discovered.length+' / 14';$('#codex-gems').textContent=g.gems;$$('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.filter===filter)));$('#codex-grid').innerHTML=Object.values(CHARACTERS).filter(s=>filter==='all'||s.type===filter).map(s=>{const unlocked=g.discovered.includes(s.key),reason=!canEdit(g)?'준비 시간에 구매':g.units.length>=CAPACITY?'용사단이 가득해요':g.gems<s.gemCost?'보석 부족':'보석으로 구매';return `<article class="codex-card ${s.type} ${unlocked?'':'locked'} ${highlight===s.key?'highlight':''}" data-codex="${s.key}" data-unlocked="${unlocked}"><div class="codex-portrait">${heroArt(s.type,s.tier)}${unlocked?'':'<span class="question">?</span>'}</div><span class="codex-type type-pill ${s.type}">${HEROES[s.type].name} · ${s.tier}단계</span><h3>${unlocked?s.name:'아직 만나지 못했어요'}</h3><span class="tier-stars">${'★'.repeat(s.tier)}</span>${unlocked?`<div class="codex-stats"><div>최대 체력<b data-stat="hp">${s.hp.toLocaleString()}</b></div><div>공격력<b data-stat="power">${s.power.toLocaleString()}</b></div></div><p>${s.story}</p><button class="gem-buy" data-gembuy="${s.key}" ${reason!=='보석으로 구매'?'disabled':''} aria-label="${s.name} 보석 ${s.gemCost}개로 구매">${reason} <b>◆ ${s.gemCost}</b></button>`:`<p>직접 얻으면 도감이 열려요.<br>이전 단계 친구 둘을 합체해 보세요.</p><button class="gem-buy" disabled>발견한 뒤 구매할 수 있어요</button>`}</article>`;}).join('');if(f&&!active.isConnected){const e=$(f);if(e&&!e.disabled)e.focus({preventScroll:true});}}
for(const id of ['#codex','#codex-mobile','#codex-note'])$(id).onclick=()=>openCodex();$$('[data-filter]').forEach(b=>b.onclick=()=>{filter=b.dataset.filter;renderCodex();});
$('#codex-grid').addEventListener('click',e=>{const b=e.target.closest('[data-gembuy]');if(!b)return;const r=buyFromCodex(g,b.dataset.gembuy);if(r.ok){selection=[r.id];highlight=b.dataset.gembuy;}action(r);});
$('#help').onclick=()=>openDialog('#help-dialog');$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
function confirm(title,text,fn){$('#confirm-title').textContent=title;$('#confirm-text').textContent=text;confirmAction=fn;openDialog('#confirm-dialog');}
$('#confirm-action').onclick=()=>{$('#confirm-dialog').close();confirmAction?.();};$('#restart').onclick=()=>confirm('새 모험을 시작할까요?','용사단과 돈은 처음으로 돌아가지만, 지금까지 발견한 도감은 남아요.',()=>{const muted=g.muted;g=fresh(g.discovered);g.muted=muted;selection=[1];moving=false;mode='normal';save();render();toast('도감을 간직한 채 새로운 모험을 시작해요.');});
function showResult(){const lost=g.phase==='lost',won=g.phase==='won';$('#result-art').innerHTML=heroArt('melee',won?MAX_TIER:2)+(lost?'':`<span>✦</span>${heroArt('ranged',won?MAX_TIER:2)}`);$('#result-eyebrow').textContent=lost?'TRY AGAIN, LITTLE HERO':won?'TWENTY ADVENTURES, ONE GREAT TEAM':'TOGETHER, WE DID IT!';$('#result-title').textContent=lost?'괜찮아, 다시 해 보자!':won?'우리 용사단, 정말 멋졌어요!':`${g.wave}번째 모험, 성공!`;$('#result-description').textContent=lost?'코인과 보석, 용사단은 전투 전으로 복구돼요. 합체하거나 배치를 바꿔 다시 도전해 보세요.':won?'우주 경기장 20라운드를 모두 지켰어요! 도감에서 모은 용사들을 만나 보세요.':'새 코인으로 친구를 부르고, 보석으로 도감 속 용사를 다시 살 수 있어요.';$('#result-stats').innerHTML=lost?'<div class="result-stat"><strong>그대로</strong><span>코인 · 보석 · 용사 복구</span></div>':`<div class="result-stat"><strong>+${(g.run?.earned??0)+(g.run?.reward??0)}</strong><span>얻은 코인</span></div><div class="result-stat"><strong>+${g.run?.gems??0} ◆</strong><span>승리 보석</span></div><div class="result-stat"><strong>${g.discovered.length}/14</strong><span>발견한 용사</span></div>`;$('#result-action').textContent=lost?'다시 준비하기':won?'우리 용사단 구경하기':'다음 모험 준비하기';if(!$('#result-dialog').open)$('#result-dialog').showModal();}
$('#result-action').onclick=()=>{$('#result-dialog').close();if(g.phase==='lost')retry(g);else if(g.phase==='reward')nextWave(g);save();render();};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!document.querySelector('dialog[open]')&&!['BUTTON','A','INPUT'].includes(e.target.tagName)){e.preventDefault();mainAction();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.phase==='battle'){pause(g);save();render();}});window.addEventListener('pagehide',save);
function frame(now){const dt=last?Math.min((now-last)/1000,.1):0;last=now;step(g,dt);if(g.phase!==lastPhase){lastPhase=g.phase;if(['reward','won','lost'].includes(g.phase)){save();render();showResult();sound(g.phase==='lost'?'lost':'win');}}if(g.run?.events)g.run.events.length=0;hudElapsed+=dt;if(hudElapsed>.2){hudElapsed=0;updateHUD();}renderer?.draw(g,selection[0],now,reduced);requestAnimationFrame(frame);}
render();save();try{renderer=await makeRenderer($('#world'));renderer.draw(g,selection[0],performance.now(),reduced);$('#loading').hidden=true;requestAnimationFrame(frame);if(['reward','won'].includes(g.phase))showResult();}catch(e){$('#loading').textContent='그림을 불러오지 못했어요. 새로고침해 주세요.';console.error(e);}
