import {THREE} from '../world.js';
import {distance,pathPoint,pathLength} from '../rules.js';
export const TOWERS=[{name:'화살탑',cost:55,damage:18,range:5,rate:.7,color:0x8adeaa},{name:'대포탑',cost:95,damage:42,range:4.8,rate:1.4,color:0xf5bb6b,splash:2},{name:'서리탑',cost:75,damage:9,range:4.7,rate:.8,color:0x87dcff,slow:true},{name:'번개탑',cost:145,damage:32,range:5.8,rate:.65,color:0xc29aff,chain:true}];
export class Game{
 constructor(world,ui,progress,config){Object.assign(this,{world,ui,progress,config});this.reset();}
 reset(){const w=this.world;w.clear();w.environment(0xafd2ec);w.hemi.intensity=2.5;w.sun.intensity=3;w.ground(0x82b88d,55);w.orbit(0,0,0,28,44);this.time=0;this.cash=210;this.lives=25;this.wave=0;this.kills=0;this.charge=0;this.speed=1;this.active=false;this.ended=false;this.enemies=[];this.towers=[];this.projectiles=[];this.selected=null;this.spawnLeft=0;this.spawnTimer=0;this.paths=[{x:-19,z:-11},{x:-9,z:-11},{x:-9,z:3},{x:1,z:3},{x:1,z:-9},{x:11,z:-9},{x:11,z:10},{x:19,z:10}];this.length=pathLength(this.paths);
  for(let i=1;i<this.paths.length;i++){const a=this.paths[i-1],b=this.paths[i];w.box(Math.abs(a.x-b.x)+2.6,.06,Math.abs(a.z-b.z)+2.6,0xc6af84,(a.x+b.x)/2,.03,(a.z+b.z)/2);}
  this.pads=[];for(const [x,z] of [[-13,-7],[-5,-6],[-12,3],[-5,7],[-3,-1],[5,-4],[5,-13],[15,-5],[8,7],[15,5],[15,14],[0,6]]){const pad=w.cylinder(1.15,1.3,.25,0xdae6dc,x,.12,z);pad.userData.action={type:'pad',index:this.pads.length};w.ring(x,z,1,0xf5f3dc,.27);this.pads.push({x,z,mesh:pad,tower:null});}
  const castle=w.group(20,0,10);w.box(3,3,3,0xe0d7c7,0,1.5,0,castle);for(const x of [-1.6,1.6])for(const z of [-1.6,1.6]){w.cylinder(.65,.75,4,0xc9d1d8,x,2,z,castle);w.mesh(new THREE.ConeGeometry(.95,1.4,6),0x546d9e,x,4.7,z,castle);}w.box(.7,1.5,.1,0x7b6753,-1.52,.8,0,castle);w.label('지켜야 할 성',20,6,10,'#fff1ba',6);w.label('몬스터 입구',-19,3,-11,'#ffd4bd',6);
  for(let i=0;i<23;i++){const x=(Math.random()-.5)*50,z=(Math.random()-.5)*43;if(this.paths.every(p=>distance({x,z},p)>4)&&this.pads.every(p=>distance({x,z},p)>3))w.tree(x,z,.8+Math.random()*.5);}
  this.ui.goal('동그란 건설 칸을 눌러 타워를 세우세요. 준비되면 웨이브 시작!');this.controls();this.hud();this.ui.actions([{key:'KeyE',label:'다음 공격',action:()=>this.nextWave()},{key:'KeyQ',label:'유성 강타',action:()=>this.ultimate()}]);
 }
 pick(action){if(action?.type==='pad'){this.selected=this.pads[action.index];this.showRange();this.controls();}else if(action?.type==='tower'){this.selected=this.pads[action.index];this.showRange();this.controls();}}
 controls(){const p=this.selected,t=p?.tower,items=[{label:this.active?'웨이브 진행 중':`웨이브 ${this.wave+1} 시작`,disabled:this.active||this.ended,click:()=>this.nextWave()},{label:`진행 속도 ${this.speed}×`,click:()=>{this.speed=this.speed===1?2:1;this.controls();}}];
  if(!p)items.push({text:'빛나는 원형 건설 칸을 먼저 선택해 주세요.'});
  else if(!t)for(let i=0;i<TOWERS.length;i++)items.push({label:`${TOWERS[i].name} · ${TOWERS[i].cost} 골드`,click:()=>this.build(i),small:['빠르고 저렴한 단일 공격','주변 몬스터까지 폭발 피해','몬스터의 이동 속도 감소','최대 3마리에게 연쇄 번개'][i]});
  else items.push({text:`${TOWERS[t.type].name} Lv.${t.level} · 공격력 ${Math.round(TOWERS[t.type].damage*(1+(t.level-1)*.7))}`},{label:t.level===3?'최대 레벨':`강화 · ${this.upgradeCost(t)} 골드`,disabled:t.level===3,click:()=>this.upgrade()},{label:`판매 · ${Math.floor(t.invested*.7)} 골드`,click:()=>this.sell()});
  items.push({label:`유성 강타 · 에너지 ${Math.floor(this.charge)}/100`,disabled:this.charge<100||!this.active,click:()=>this.ultimate()});this.ui.controls('요새 지휘소',items);
 }
 build(type){if(!this.selected||this.selected.tower||this.ended)return false;const data=TOWERS[type];if(!data||this.cash<data.cost){this.ui.toast('골드가 부족해요.');return false;}this.cash-=data.cost;const pad=this.selected,g=this.world.group(pad.x,.25,pad.z),index=this.pads.indexOf(pad);g.userData.action={type:'tower',index};this.world.cylinder(.65,.85,1.1,0x647989,0,.55,0,g);this.world.cylinder(.8,.7,.25,data.color,0,1.2,0,g);const turret=new THREE.Group();turret.position.y=1.45;g.add(turret);if(type===1){this.world.sphere(.55,0x506173,0,0,0,turret);const barrel=this.world.cylinder(.19,.24,1.1,0x3d4c61,0,.1,.6,turret);barrel.rotation.x=Math.PI/2;}else if(type===0){this.world.box(1.25,.1,.18,data.color,0,.25,0,turret);this.world.box(.15,.2,1,0x736247,0,.23,.15,turret);}else{this.world.mesh(new THREE.OctahedronGeometry(.55),data.color,0,.5,0,turret,{emissive:data.color,emissiveIntensity:.6});this.world.cylinder(.05,.05,.9,0xe4eaf0,0,.1,0,turret);}
  const tower={type,level:1,cooldown:0,mesh:g,turret,pad,invested:data.cost};pad.tower=tower;this.towers.push(tower);this.world.burst(pad.x,1,pad.z,data.color);this.ui.sound('build');this.controls();this.hud();this.showRange();return true;}
 upgradeCost(t){return Math.floor(TOWERS[t.type].cost*(.7+t.level*.4));}
 upgrade(){const t=this.selected?.tower;if(!t||t.level>=3)return;const cost=this.upgradeCost(t);if(this.cash<cost){this.ui.toast('강화할 골드가 부족해요.');return;}this.cash-=cost;t.invested+=cost;t.level++;t.turret.scale.setScalar(1+(t.level-1)*.18);this.world.burst(t.pad.x,2,t.pad.z,0xffe799,24);this.controls();this.showRange();}
 sell(){const t=this.selected?.tower;if(!t)return;this.cash+=Math.floor(t.invested*.7);this.world.remove(t.mesh);this.towers=this.towers.filter(x=>x!==t);this.selected.tower=null;this.controls();this.showRange();}
 showRange(){if(this.range)this.world.remove(this.range);this.range=null;const t=this.selected?.tower;if(t)this.range=this.world.ring(t.pad.x,t.pad.z,TOWERS[t.type].range+(t.level-1)*.6,TOWERS[t.type].color);}
 nextWave(){if(this.active||this.ended)return;this.wave++;this.active=true;this.spawnLeft=5+this.wave*2;this.spawnTimer=.2;this.ui.goal(this.wave%5===0?`웨이브 ${this.wave} · 거대 보스 등장!`:`웨이브 ${this.wave} · 성에 닿기 전에 막아 주세요.`);this.controls();}
 spawn(){const boss=this.wave%5===0&&this.spawnLeft===1,fast=!boss&&this.spawnLeft%4===0,armored=!boss&&this.spawnLeft%5===0,hp=(35*Math.pow(1.17,this.wave-1)+(boss?this.wave*100:0))*[.65,1,1.5][this.config.difficulty]*(armored?1.7:1);const mesh=this.world.creature(boss?2:fast?1:armored?4:0,boss?0x966ccc:fast?0xe4bd6a:armored?0x8097aa:0x83bf72);mesh.scale.setScalar(boss?1.9:1);const p=pathPoint(this.paths,0);mesh.position.set(p.x,0,p.z);this.enemies.push({mesh,hp,maxHp:hp,d:0,speed:boss?1.35:fast?2.8:1.65,slow:0,boss,armored,dead:false});}
 damage(enemy,damage){if(enemy.dead)return;enemy.hp-=damage*(enemy.armored?.78:1);if(enemy.hp<=0){enemy.dead=true;this.cash+=enemy.boss?50:10;this.kills++;this.charge=Math.min(100,this.charge+(enemy.boss?25:5));this.world.burst(enemy.mesh.position.x,.7,enemy.mesh.position.z,enemy.boss?0xd5a2ff:0xffd991,enemy.boss?30:10);this.world.remove(enemy.mesh);this.ui.sound('coin');}}
 ultimate(){if(this.charge<100||!this.active)return;this.charge=0;for(const e of this.enemies){this.damage(e,180+this.wave*12);this.world.burst(e.mesh.position.x,1,e.mesh.position.z,0xffac6e,12);}this.ui.sound('win');this.ui.toast('유성 강타! 모든 몬스터에게 큰 피해!');this.controls();}
 tick(dt){if(this.ended)return;dt*=this.speed;this.time+=dt;
  if(this.active&&this.spawnLeft>0){this.spawnTimer-=dt;if(this.spawnTimer<=0){this.spawn();this.spawnLeft--;this.spawnTimer=.62;}}
  for(const e of this.enemies){if(e.dead)continue;e.slow=Math.max(0,e.slow-dt);e.d+=dt*e.speed*(e.slow>0?.42:1);const p=pathPoint(this.paths,e.d);e.mesh.position.set(p.x,Math.abs(Math.sin(this.time*7+e.d))*.07,p.z);e.mesh.rotation.y=p.angle;if(e.d>=this.length){e.dead=true;this.lives-=e.boss?5:1;this.world.remove(e.mesh);this.ui.sound('hit');}}
  for(const t of this.towers){t.cooldown-=dt;const spec=TOWERS[t.type],range=spec.range+(t.level-1)*.6,targets=this.enemies.filter(e=>!e.dead&&distance(t.pad,e.mesh.position)<range).sort((a,b)=>b.d-a.d);if(targets[0]){const target=targets[0];t.turret.rotation.y=Math.atan2(target.mesh.position.x-t.pad.x,target.mesh.position.z-t.pad.z);if(t.cooldown<=0){t.cooldown=spec.rate/(1+(t.level-1)*.13);const hit=spec.damage*(1+(t.level-1)*.7);const from=new THREE.Vector3(t.pad.x,2,t.pad.z),to=target.mesh.position.clone().add(new THREE.Vector3(0,.7,0));this.world.beam(from,to,spec.color,t.type===1?.14:.045);this.damage(target,hit);if(spec.slow)target.slow=2;if(spec.splash)for(const e of this.enemies)if(e!==target&&!e.dead&&distance(e.mesh.position,to)<spec.splash)this.damage(e,hit*.55);if(spec.chain)for(const e of targets.slice(1,3)){this.world.beam(to,e.mesh.position.clone().add(new THREE.Vector3(0,.7,0)),spec.color,.04);this.damage(e,hit*.65);}t.turret.position.y=1.38;}}t.turret.position.y+=(1.45-t.turret.position.y)*Math.min(1,dt*12);}
  this.enemies=this.enemies.filter(e=>!e.dead);
  if(this.lives<=0){this.finish(false);return;}
  if(this.active&&!this.spawnLeft&&!this.enemies.length){this.active=false;const bonus=25+this.wave*3;this.cash+=bonus;this.ui.reward(5+this.wave,false);this.progress.best=Math.max(this.progress.best,this.wave);this.ui.save();this.ui.toast(`웨이브 ${this.wave} 방어 성공! +${bonus} 골드`);this.ui.goal('타워를 강화하고 다음 웨이브에 도전하세요.');this.controls();if(this.wave===20)this.finish(true);}
  this.hud();
 }
 hud(){this.ui.stats([{label:'성의 체력',value:Math.max(0,this.lives)+' / 25'},{label:'웨이브',value:this.wave+' / 20'},{label:'골드',value:this.cash},{label:'유성 에너지',value:Math.floor(this.charge)+'%'}]);}
 finish(won){if(this.ended)return;this.ended=true;this.progress.best=Math.max(this.progress.best,Math.max(0,this.wave-(this.active?1:0)));if(won)this.progress.wins++;this.ui.reward(won?200:Math.max(10,this.wave*5));this.ui.save();this.ui.end(won?'요새를 지켜냈어요!':'다음에는 더 튼튼한 요새로!',`${this.kills}마리를 막았어요. 최고 기록 ${this.progress.best} 웨이브`,()=>this.reset());}
}
