import {THREE,movePlayer} from '../world.js';
import {AVATAR_COLORS,distance,clamp} from '../rules.js';
export class Game{
 constructor(world,ui,progress,config){Object.assign(this,{world,ui,progress,config});this.role='explorer';this.reset(!!progress.run);}
 reset(resume=false){const saved=resume?this.progress.run:null,w=this.world;const val=(key,fallback)=>Number.isFinite(Number(saved?.[key]))?Number(saved[key]):fallback;w.clear();w.environment(0x8bb1c5);w.ground(0x47755d,72);w.hemi.intensity=2.8;w.sun.intensity=3;this.time=0;this.phase=0;this.day=clamp(Math.floor(Number(saved?.day)||1),1,99);this.health=clamp(val('health',100),1,130);this.hunger=clamp(val('hunger',100),0,100);this.fuel=clamp(val('fuel',100),0,150);this.wood=clamp(val('wood',0),0,999);this.stone=clamp(val('stone',0),0,999);this.food=clamp(val('food',3),0,999);this.rescued=clamp(val('rescued',0),0,4);this.role=['explorer','knight','chef'].includes(saved?.role)?saved.role:this.role;this.maxHealth=this.role==='knight'?130:100;if(!saved)this.health=this.maxHealth;this.ended=false;this.resources=[];this.enemies=[];this.children=[];this.structures=[];this.attackCD=0;this.interactCD=0;this.actionPose=0;this.spawnTimer=0;this.invincible=0;
  this.player=w.character(AVATAR_COLORS[this.progress.color]);this.player.position.set(0,0,5);w.follow(this.player.position);
  w.cylinder(4,4.3,.2,0x8b8267,0,.1,0);for(let i=0;i<8;i++){const a=i*Math.PI/4;w.rock(Math.cos(a)*1.4,Math.sin(a)*1.4,.3);}for(const angle of [-.65,.65]){const log=w.cylinder(.2,.2,2.3,0x70503b,0,.35,0);log.rotation.z=Math.PI/2;log.rotation.y=angle;}
  this.flame=w.group(0,.4,0);w.mesh(new THREE.ConeGeometry(.65,1.7,7),0xffa34d,0,.8,0,this.flame,{emissive:0xff722a,emissiveIntensity:1.4});w.mesh(new THREE.ConeGeometry(.35,1.2,6),0xffe58c,0,.7,.1,this.flame,{emissive:0xffdc61,emissiveIntensity:1.2});this.fireLight=new THREE.PointLight(0xffba6d,35,18,1.7);this.fireLight.position.set(0,2,0);w.stage.add(this.fireLight);w.label('모닥불 · E로 나무 넣기',0,3.5,0,'#ffe0a9',6);
  for(let i=0;i<48;i++){const angle=i*2.399,rad=8+(i%6)*3.6,x=Math.cos(angle)*rad,z=Math.sin(angle)*rad,type=i%5===0?'stone':i%4===0?'food':'wood';let mesh;if(type==='wood')mesh=w.tree(x,z,.8+(i%3)*.15);else if(type==='stone')mesh=w.rock(x,z,.8);else{mesh=w.group(x,0,z);w.sphere(.6,0x55885e,0,.5,0,mesh);for(const side of [-1,1])w.sphere(.13,0xf1a0a6,side*.3,.85,.3,mesh);}mesh.userData.action={type:'resource',index:this.resources.length};this.resources.push({type,x,z,mesh,left:type==='wood'?4:3,cooldown:0});}
  const lake=w.cylinder(4,4,.12,0x5daec1,-20,.03,2,w.stage,{metalness:.3,roughness:.25});lake.scale.z=.65;
  for(let i=0;i<4;i++){const angle=i*Math.PI/2+.5,mesh=w.character([0xf4c776,0xe7a3be,0x9cbbef,0xb5dc89][i],{scale:.65});mesh.position.set(Math.cos(angle)*22,0,Math.sin(angle)*22);if(i<this.rescued){mesh.position.set(-3+i*2,0,4);this.children.push({mesh,rescued:true,following:false});}else{w.label('도와줘요!',mesh.position.x,2.3,mesh.position.z,'#fff3b0',3.5);this.children.push({mesh,rescued:false,following:false});}}
  const savedStructures=Array.isArray(saved?.structures)?saved.structures.slice(0,8):[];for(const type of savedStructures)if(['wall','tower'].includes(type))this.addStructure(type,true);
  this.ui.goal(resume?`${this.day}일째 아침에서 이어 시작해요.`:'낮에는 자원을 모으고, 밤에는 모닥불 근처에서 숲의 생물들을 막으세요.');this.controls();this.ui.actions([{key:'KeyE',label:'채집 / 모닥불',action:()=>this.interact()},{key:'Space',label:'공격',action:()=>this.attack()},{key:'KeyQ',label:'음식 먹기',action:()=>this.eat()}]);this.saveRun();this.hud();
 }
 controls(){this.ui.controls('숲속 생존 준비',[
  {label:'클래스',options:[['explorer','탐험가 · 채집 +1'],['knight','기사 · 체력 130'],['chef','요리사 · 식사 회복 +15']],value:this.role,change:v=>this.ui.confirm('클래스를 바꿀까요?','현재 탐험을 마치고 1일째부터 새 클래스로 시작해요.',()=>{this.role=v;this.progress.run=null;this.reset();})},
  {label:'방벽 건설 · 나무 8',small:'모닥불에 접근한 적을 밀어내요.',click:()=>this.addStructure('wall')},
  {label:'수호탑 건설 · 나무 10 + 돌 6',small:'근처의 적을 자동으로 공격해요.',click:()=>this.addStructure('tower')},
  {label:'도끼 강화 · '+(80*(1+(this.progress.upgrades.axe||0)))+' 코인',disabled:(this.progress.upgrades.axe||0)>=4,click:()=>{if(this.ui.spend(80*(1+(this.progress.upgrades.axe||0)))){this.progress.upgrades.axe=(this.progress.upgrades.axe||0)+1;this.ui.save();this.controls();}}},
  {text:'아이들을 가까이에서 만나 모닥불로 데려오세요. 구조한 아이들이 매일 자원을 모아 줘요. 해가 뜰 때 탐험을 저장해요.'}
 ]);}
 addStructure(type,free=false){if(this.structures.length>=8){this.ui.toast('캠프 건설 칸이 모두 찼어요.');return false;}const wood=type==='wall'?8:10,stone=type==='wall'?0:6;if(!free&&(this.wood<wood||this.stone<stone)){this.ui.toast('건설할 재료가 부족해요.');return false;}if(!free){this.wood-=wood;this.stone-=stone;}const angle=this.structures.length*Math.PI/4,x=Math.cos(angle)*5.5,z=Math.sin(angle)*5.5,g=this.world.group(x,0,z);if(type==='wall'){for(let i=-2;i<=2;i++)this.world.cylinder(.14,.2,1.6,0x9a7755,i*.36,.8,0,g);g.rotation.y=-angle+Math.PI/2;}else{for(const side of [-1,1])this.world.box(.2,2,.2,0x967952,side*.45,1,0,g);this.world.box(1.3,.25,1.3,0xd2c396,0,1.8,0,g);this.world.mesh(new THREE.OctahedronGeometry(.38),0x8fd5ff,0,2.25,0,g,{emissive:0x75b8ef,emissiveIntensity:.5});}this.structures.push({type,mesh:g,x,z,cooldown:0});this.world.burst(x,.8,z,0xe6ca8f,18);if(!free){this.ui.sound('build');this.saveRun();}return true;}
 interact(){if(this.ended||this.interactCD>0)return;this.interactCD=.4;if(distance(this.player.position,{x:0,z:0})<3.5){if(this.wood){const count=Math.min(5,this.wood);this.wood-=count;this.fuel=clamp(this.fuel+count*10,0,150);this.world.burst(0,1,0,0xffc065,16);this.ui.toast('모닥불이 따뜻해졌어요!');}else this.ui.toast('모닥불에 넣을 나무를 모아 주세요.');return;}
  const resource=this.resources.filter(r=>r.left>0&&distance(r,this.player.position)<2.7).sort((a,b)=>distance(a,this.player.position)-distance(b,this.player.position))[0];if(!resource){this.ui.toast('나무·돌·열매 가까이에서 채집하세요.');return;}const gain=1+(this.role==='explorer'?1:0);this[resource.type==='food'?'food':resource.type]+=gain;resource.left--;this.actionPose=.3;this.world.burst(resource.x,1,resource.z,{wood:0xcfb885,stone:0xcedbe5,food:0xfba9ba}[resource.type],10);this.ui.sound('coin');if(!resource.left){resource.mesh.visible=false;resource.cooldown=40;}this.hud();
 }
 attack(){if(this.attackCD>0||this.ended)return;this.attackCD=.45;this.actionPose=.35;const from=this.player.position;const damage=(this.role==='knight'?34:25)+(this.progress.upgrades.axe||0)*9;this.world.burst(from.x,.9,from.z,0xb8eaf3,7);for(const e of this.enemies)if(!e.dead&&distance(e.mesh.position,from)<3){this.damage(e,damage);const dx=e.mesh.position.x-from.x,dz=e.mesh.position.z-from.z,n=Math.hypot(dx,dz)||1;e.mesh.position.x+=dx/n*.65;e.mesh.position.z+=dz/n*.65;}this.ui.sound('jump');}
 damage(e,damage){if(e.dead)return;e.hp-=damage;if(e.hp<=0){e.dead=true;this.world.burst(e.mesh.position.x,1,e.mesh.position.z,e.boss?0xd0a5e8:0xa6d4ce,18);this.world.remove(e.mesh);this.ui.reward(e.boss?30:4,false);if(Math.random()<.25)this.food++;}}
 eat(){if(!this.food){this.ui.toast('열매 덤불에서 음식을 구해 주세요.');return;}if(this.health>=this.maxHealth&&this.hunger>=95){this.ui.toast('지금은 배부르고 건강해요!');return;}this.food--;this.hunger=clamp(this.hunger+35,0,100);this.health=clamp(this.health+20+(this.role==='chef'?15:0),0,this.maxHealth);this.ui.sound('coin');}
 spawnEnemy(){const boss=this.day%5===0&&!this.bossSpawned,angle=Math.random()*Math.PI*2,mesh=this.world.creature(boss?2:1,boss?0x76628a:0x879eac);mesh.scale.setScalar(boss?2:1);mesh.position.set(Math.cos(angle)*24,0,Math.sin(angle)*24);this.enemies.push({mesh,hp:(boss?160+this.day*12:35+this.day*3)*[.7,1,1.35][this.config.difficulty],speed:boss?1.25:1.6+Math.min(1.5,this.day*.04),cooldown:0,dead:false,boss});if(boss){this.bossSpawned=true;this.ui.toast('거대한 숲의 수호자가 나타났어요!');}}
 saveRun(){this.progress.run={day:this.day,health:this.health,hunger:this.hunger,fuel:this.fuel,wood:this.wood,stone:this.stone,food:this.food,rescued:this.rescued,role:this.role,structures:this.structures.map(s=>s.type)};this.ui.save();}
 tick(dt,input){if(this.ended)return;this.time+=dt;this.phase+=dt;const night=this.phase>=32;this.attackCD-=dt;this.interactCD-=dt;this.actionPose=Math.max(0,this.actionPose-dt);this.invincible=Math.max(0,this.invincible-dt);
  const speed=movePlayer(this.player,input,dt,this.hunger>0?5.5:3.5,29);this.world.animateCharacter(this.player,speed,this.time,this.actionPose?this.actionPose/.35:0);this.hunger=Math.max(0,this.hunger-dt*.18);if(!this.hunger)this.health-=dt*1.3;this.fuel=Math.max(0,this.fuel-dt*(night?.38:.09));if(this.fuel===0&&night)this.health-=dt*.55;
  this.flame.scale.setScalar((.55+Math.min(1,this.fuel/100))*(.95+Math.sin(this.time*9)*.05));this.fireLight.intensity=this.fuel>0?30+Math.sin(this.time*8)*3:0;this.flame.visible=this.fuel>0;
  const sky=new THREE.Color(night?0x152537:0x8bb1c5);this.world.scene.background.lerp(sky,dt*.7);this.world.scene.fog.color.copy(this.world.scene.background);this.world.hemi.intensity+=(night?1.3-this.world.hemi.intensity:2.8-this.world.hemi.intensity)*Math.min(1,dt);this.world.sun.intensity+=(night?.25-this.world.sun.intensity:3-this.world.sun.intensity)*Math.min(1,dt);
  if(night){this.spawnTimer-=dt;if(this.spawnTimer<=0&&this.enemies.length<18){this.spawnEnemy();this.spawnTimer=Math.max(1.3,4.5-this.day*.06);}if(!this.nightNotified){this.nightNotified=true;this.ui.goal('밤이 왔어요! 적을 막고 모닥불을 지켜 주세요.');this.ui.sound('hit');}}
  for(const e of this.enemies){if(e.dead)continue;e.cooldown-=dt;const target=distance(e.mesh.position,this.player.position)<9?this.player.position:{x:0,z:0};const dx=target.x-e.mesh.position.x,dz=target.z-e.mesh.position.z,d=Math.hypot(dx,dz)||1;let slow=1;if(this.fuel>0&&distance(e.mesh.position,{x:0,z:0})<4)slow=.65;for(const wall of this.structures)if(wall.type==='wall'&&distance(wall,e.mesh.position)<1.2)slow=.15;e.mesh.position.x+=dx/d*e.speed*dt*slow;e.mesh.position.z+=dz/d*e.speed*dt*slow;e.mesh.rotation.y=Math.atan2(dx,dz);e.mesh.position.y=Math.abs(Math.sin(this.time*6+e.hp))*.1;
    if(e.cooldown<=0&&distance(e.mesh.position,this.player.position)<1.1){e.cooldown=1;this.health-=e.boss?14:7;this.ui.sound('hit');}else if(e.cooldown<=0&&distance(e.mesh.position,{x:0,z:0})<1.5){e.cooldown=1.2;this.fuel=Math.max(0,this.fuel-5);}
  }
  for(const tower of this.structures){if(tower.type!=='tower')continue;tower.cooldown-=dt;const target=this.enemies.find(e=>!e.dead&&distance(tower,e.mesh.position)<7);if(target&&tower.cooldown<=0){tower.cooldown=.8;this.world.beam(new THREE.Vector3(tower.x,2.3,tower.z),target.mesh.position.clone().add(new THREE.Vector3(0,.7,0)),0xa2ddff);this.damage(target,20);}}
  this.enemies=this.enemies.filter(e=>!e.dead);
  for(const child of this.children){if(child.rescued)continue;if(distance(child.mesh.position,this.player.position)<2)child.following=true;if(child.following){const dx=this.player.position.x-child.mesh.position.x,dz=this.player.position.z-child.mesh.position.z,n=Math.hypot(dx,dz);if(n>1.1){child.mesh.position.x+=dx/n*4.7*dt;child.mesh.position.z+=dz/n*4.7*dt;child.mesh.rotation.y=Math.atan2(dx,dz);this.world.animateCharacter(child.mesh,4,this.time);}if(distance(child.mesh.position,{x:0,z:0})<5){child.rescued=true;this.rescued++;this.ui.reward(60);this.world.burst(child.mesh.position.x,1,child.mesh.position.z,0xffe29b,25);this.ui.toast('아이를 구했어요! 매일 나무와 음식을 도와줘요.');this.saveRun();}}}
  for(const r of this.resources){if(!r.left){r.cooldown-=dt;if(r.cooldown<=0){r.left=r.type==='wood'?4:3;r.mesh.visible=true;}}}
  if(this.health<=0){this.finish(false);return;}
  if(this.phase>=54){if(this.day>=99){this.finish(true);return;}this.day++;this.phase=0;this.nightNotified=false;this.bossSpawned=false;this.spawnTimer=0;this.enemies.forEach(e=>this.world.remove(e.mesh));this.enemies=[];this.wood+=this.rescued*2;this.food+=this.rescued;this.health=clamp(this.health+8,0,this.maxHealth);this.ui.reward(15,false);this.progress.best=Math.max(this.progress.best,this.day-1);this.saveRun();this.ui.toast(`${this.day}일째 아침! 탐험을 저장했어요.`);this.ui.goal('해가 떴어요. 나무와 음식, 방벽을 준비해 주세요.');}
  this.hud();
 }
 hud(){this.ui.stats([{label:'생존',value:`${this.day}일 · ${this.phase>=32?'밤':'낮'}`},{label:'체력 / 배부름',value:`${Math.ceil(Math.max(0,this.health))} / ${Math.ceil(this.hunger)}`},{label:'불 / 구조',value:`${Math.ceil(this.fuel)}% · ${this.rescued}/4`},{label:'나무 · 돌 · 음식',value:`${this.wood} · ${this.stone} · ${this.food}`}]);}
 finish(won){if(this.ended)return;this.ended=true;this.progress.best=Math.max(this.progress.best,this.day-1+(won?1:0));this.progress.run=null;if(won)this.progress.wins++;this.ui.reward(won?990:Math.max(10,this.day*5));this.ui.save();this.ui.end(won?'99일의 기적!':'숲속 모험을 마쳤어요.',`${this.day}일 동안 함께했어요. 구조한 아이 ${this.rescued}명 · 최고 생존 ${this.progress.best}일`,()=>this.reset());}
 pick(action,point){if(action?.type==='resource'&&distance(this.resources[action.index],this.player.position)<2.7)this.interact();else this.ui.input.target={x:clamp(point.x,-29,29),z:clamp(point.z,-29,29)};}
}
