import {THREE,movePlayer} from '../world.js';
import {fashionScore,clamp} from '../rules.js';
export const COLORS=[0xf39bc0,0x98cdf5,0xbb9be2,0xb8ddb5,0xf2d78e,0xf4f0e8,0xdb8b99,0x83dace];
export const STYLES=['로열 드레스','요정 드레스','얼음 드레스','발레 드레스','별빛 드레스','인어 드레스','꽃잎 드레스'];
export const THEMES=[{name:'황금 왕국의 무도회',color:4,style:0,wings:0},{name:'숲속 요정의 축제',color:3,style:1,wings:1},{name:'겨울 왕국의 밤',color:1,style:2,wings:0},{name:'핑크 발레 파티',color:0,style:3,wings:0},{name:'별빛 날개의 꿈',color:2,style:4,wings:2},{name:'바다 공주의 초대',color:7,style:5,wings:0},{name:'꽃잎 정원의 하루',color:6,style:6,wings:1}];
export function safeOutfit(o={}){return {color:clamp(Math.floor(Number(o.color)||0),0,7),style:clamp(Math.floor(Number(o.style)||0),0,6),hair:clamp(Math.floor(Number(o.hair)||0),0,3),crown:clamp(Math.floor(Number(o.crown??1)||0),0,3),wings:clamp(Math.floor(Number(o.wings)||0),0,2),pet:clamp(Math.floor(Number(o.pet)||0),0,3)};}
export class Game{
 constructor(world,ui,progress,config){Object.assign(this,{world,ui,progress,config});this.outfit=safeOutfit(progress.outfit||{});this.mode='dress';this.themeIndex=Math.floor(Math.random()*THEMES.length);this.reset();}
 reset(){this.ui.movement?.(this.mode==='hearts');const w=this.world;w.clear();w.environment(0xbecdec,0xccd7ed);w.hemi.intensity=3;w.sun.intensity=2.6;w.ground(0xd8cfde,55);this.time=0;this.ended=false;this.runway=0;this.runwayScored=false;this.roundTime=0;this.hearts=[];this.caught=0;this.missed=0;this.spawnTimer=0;this.cakeLayers=2;this.cakeFlavor=0;this.cakeTopping=0;this.cakeOrder={layers:3,flavor:1,topping:2};
  w.cylinder(6.5,7,.45,0xebe2ee,0,.225,0);w.ring(0,0,5.8,0xe6b768,.46);w.box(4,.2,19,0xf3bfd5,0,.2,8);for(let i=0;i<9;i++){w.sphere(.13,0xfff2ce,-2.15,.4,i*2,w.stage,{emissive:0xffe5b0,emissiveIntensity:1});w.sphere(.13,0xfff2ce,2.15,.4,i*2,w.stage,{emissive:0xffe5b0,emissiveIntensity:1});}
  for(const side of [-1,1]){for(let i=0;i<3;i++){const x=side*(8+i*.9),z=-7-i*3;w.cylinder(.85,1,5+i,0xf0e5e7,x,(5+i)/2,z);w.mesh(new THREE.ConeGeometry(1.4,2,8),0xa8a5d3,x,6+i,z);w.box(.45,1,.05,0xeab967,x,3,z+1);}
    for(let i=0;i<8;i++)w.flower(side*(5+Math.random()*7),-6+i*3,[0xeeb8d2,0xc5b4ef,0xffe6ad][i%3]);}
  for(let i=0;i<3;i++){const judge=w.character([0x8fb9d4,0xd8b275,0xb898d4][i]);judge.position.set(-5,0,6+i*3);judge.rotation.y=Math.PI/2;w.box(1.5,.7,1.5,0xbbacbd,-5,.35,6+i*3);}
  w.label('ROYAL DREAM',0,5,-6,'#fff1c9',8);this.buildPrincess();w.orbit(0,1,0,13);this.ui.goal('드레스·머리·왕관·날개·펫을 골라 나만의 공주를 완성해요.');this.controls();this.ui.actions([{key:'KeyE',label:'런웨이 출발',action:()=>this.startRunway()},{key:'Space',label:'빙글빙글',action:()=>this.twirl()}]);this.hud();
 }
 buildPrincess(){const w=this.world;if(this.princess)w.remove(this.princess);if(this.pet)w.remove(this.pet);const o=this.outfit,g=w.character(COLORS[o.color]);g.position.set(0,.46,0);this.princess=g;g.userData.body.material=w.mat(COLORS[o.color]);g.userData.head.material=w.mat(0xffdcc4);
  const dress=new THREE.Group();dress.position.y=.15;g.add(dress);const radius=[.8,.68,.75,.85,.8,.48,.86][o.style],height=o.style===3?.5:.85;w.cylinder(.27,radius,height,COLORS[o.color],0,height/2,0,dress,{roughness:.52,metalness:.08});w.cylinder(radius*.92,radius*1.07,.12,0xffeef8,0,.08,0,dress);for(let i=0;i<10;i++){const angle=i*Math.PI/5;w.sphere(.045,0xffe6a6,Math.sin(angle)*radius*.85,.2,Math.cos(angle)*radius*.85,dress,{metalness:.5,roughness:.3});}if(o.style===6)for(let i=0;i<6;i++){const petal=w.sphere(.35,COLORS[o.color],Math.sin(i*Math.PI/3)*.55,.55,Math.cos(i*Math.PI/3)*.55,dress);petal.scale.set(.6,1,.6);}if(o.style===5){const tail=w.sphere(.4,COLORS[o.color],0,.08,-.35,dress);tail.scale.set(1.5,.2,.65);}g.userData.dress=dress;
  const hairColors=[0x795239,0x383044,0xd4a65c,0xcc8699],hair=w.sphere(.32,hairColors[o.hair],0,1.76,-.04,g);hair.scale.set(1,.9,1);for(const side of [-1,1]){const lock=w.sphere(.15,hairColors[o.hair],side*.29,1.49,-.04,g);lock.scale.set(1,o.hair===1?1.2:2.2,1);}if(o.hair===2)w.sphere(.22,hairColors[o.hair],0,2.05,-.05,g);
  if(o.crown){const gold=[0,0xf2c971,0xe8eefa,0xc0a1ef][o.crown];w.cylinder(.29,.3,.15,gold,0,1.99,0,g,{metalness:.65,roughness:.3});for(let i=0;i<5;i++){const a=i*Math.PI*2/5;w.mesh(new THREE.ConeGeometry(.055,.22,5),gold,Math.sin(a)*.27,2.14,Math.cos(a)*.27,g);w.sphere(.055,0xf3a6c7,Math.sin(a)*.27,2.27,Math.cos(a)*.27,g);}}
  this.wings=[];if(o.wings)for(const side of [-1,1]){const wing=new THREE.Group();wing.position.set(side*.27,1.15,-.25);g.add(wing);const upper=w.sphere(.62,o.wings===1?0xd0f0df:0xd9c6ef,side*.43,.25,0,wing,{transparent:true,opacity:.8,metalness:.15});upper.scale.set(.85,1.1,.08);const lower=w.sphere(.42,0xf8dbea,side*.32,-.28,0,wing,{transparent:true,opacity:.85});lower.scale.set(.9,1,.08);wing.userData.side=side;this.wings.push(wing);}
  this.pet=null;if(o.pet){this.pet=w.creature(o.pet,[0,0xf1c9b0,0xbedbfa,0xdbc3ee][o.pet]);this.pet.scale.setScalar(.5);this.pet.position.set(1.5,.46,0);}
  this.progress.outfit={...o};this.ui.save();
 }
 controls(){const o=this.outfit,items=[{label:'스튜디오 모드',options:[['dress','공주 옷장'],['show','패션쇼 도전'],['hearts','하트 캐치'],['cake','케이크 공방']],value:this.mode,change:v=>this.changeMode(v)}];
  if(this.mode==='dress'||this.mode==='show'){
    if(this.mode==='show')items.push({text:'이번 주제: '+THEMES[this.themeIndex].name+' · '+['핑크','하늘','보라','민트','골드','크림','장미','바다'][THEMES[this.themeIndex].color]+' / '+STYLES[THEMES[this.themeIndex].style]+' / '+['날개 없음','요정 날개','별빛 날개'][THEMES[this.themeIndex].wings]});
    for(const [key,label,options] of [['style','드레스',STYLES],['color','색상',['핑크','하늘','보라','민트','골드','크림','장미','바다']],['hair','헤어',['초콜릿 웨이브','밤색 단발','금빛 올림머리','로즈 웨이브']],['crown','왕관',['없음','황금 왕관','크리스털 왕관','보라 보석 왕관']],['wings','날개',['없음','요정 날개','별빛 날개']],['pet','펫',['없음','토끼','하늘 여우','작은 드래곤']]])items.push({label,options:options.map((name,i)=>[String(i),name]),value:String(o[key]),change:v=>{o[key]=Number(v);this.buildPrincess();}});
    items.push({label:this.runway?'런웨이 진행 중':'런웨이 출발',disabled:!!this.runway,click:()=>this.startRunway()});
  }else if(this.mode==='hearts')items.push({text:'좌우로 움직이며 45초 동안 떨어지는 하트를 받아요! 보라 별은 피하세요.'},{label:'하트 캐치 다시 시작',click:()=>this.changeMode('hearts')});
  else{
    items.push({text:'오늘의 주문: 3단 딸기 케이크 + 별 장식'});
    for(const [key,label,options] of [['cakeLayers','케이크 높이',[[1,'1단'],[2,'2단'],[3,'3단'],[4,'4단']]],['cakeFlavor','맛',[[0,'바닐라'],[1,'딸기'],[2,'초콜릿'],[3,'블루베리']]],['cakeTopping','장식',[[0,'촛불'],[1,'체리'],[2,'반짝 별']]]])items.push({label,options:options.map(([value,name])=>[String(value),name]),value:String(this[key]),change:v=>{this[key]=Number(v);this.buildCake();}});
    items.push({label:'완성해서 주문 전달',click:()=>this.finishCake()});
  }
  this.ui.controls(this.mode==='cake'?'달콤한 케이크 공방':'공주 스타일링',items);
 }
 changeMode(mode){this.mode=mode;this.reset();if(mode==='hearts'){this.world.orbit(0,1,0,17);if(this.world.controls)this.world.controls.enabled=false;this.ui.goal('좌우로 움직여 하트를 받아요! 보라색 별은 피하세요.');}else if(mode==='cake'){this.princess.visible=false;if(this.pet)this.pet.visible=false;this.buildCake();this.world.orbit(0,1,0,11);this.ui.goal('주문에 맞춰 맛과 높이, 장식을 골라 주세요.');}else if(mode==='show')this.ui.goal('주제에 맞게 공주를 꾸민 다음 런웨이로 출발하세요.');this.controls();}
 twirl(){if(this.mode==='cake')return;this.twirlTime=1.4;this.world.burst(this.princess.position.x,1.5,this.princess.position.z,0xffd89b,22);this.ui.sound('jump');}
 startRunway(){if(this.runway||this.mode==='hearts'||this.mode==='cake')return;this.runway=.001;this.runwayScored=false;this.world.orbit(0,1,5,19);this.ui.goal('런웨이의 주인공! 앞쪽으로 걸어가서 멋진 포즈를 보여줘요.');this.controls();this.ui.sound('win');}
 runwayComplete(){if(this.runwayScored)return;this.runwayScored=true;const score=this.mode==='show'?fashionScore(this.outfit,THEMES[this.themeIndex]):75;const reward=this.mode==='show'?Math.floor(score/2):15;this.ui.reward(reward);this.progress.best=Math.max(this.progress.best,score);if(score>=90)this.progress.wins++;this.ui.save();this.world.burst(0,2,8,0xffcddd,45);this.world.burst(1,2,7,0xffdf8a,30);this.ui.toast(`패션쇼 ${score}점! +${reward} 하트`);if(this.mode==='show'){this.themeIndex=(this.themeIndex+1)%THEMES.length;this.ui.goal('다음 주제: '+THEMES[this.themeIndex].name);}else this.ui.goal('멋진 런웨이였어요! 옷을 바꿔 다른 스타일도 만들어 보세요.');this.controls();}
 buildCake(){if(this.cake)this.world.remove(this.cake);const w=this.world,g=w.group(0,.46,0);this.cake=g;const colors=[0xffedd2,0xf4a8bd,0x8a5f50,0xbaa6e0],color=colors[this.cakeFlavor];w.cylinder(1.65,1.7,.15,0xf7f4ee,0,.08,0,g);for(let i=0;i<this.cakeLayers;i++){const r=1.35-i*.22,y=.35+i*.55;w.cylinder(r,r,.5,color,0,y,0,g);w.cylinder(r+.03,r+.03,.1,0xfff3e4,0,y+.24,0,g);for(let j=0;j<10;j++){const a=j*Math.PI/5;w.sphere(.075,0xffe4ea,Math.cos(a)*r,y+.27,Math.sin(a)*r,g);}}
  const top=.15+this.cakeLayers*.55;if(this.cakeTopping===0){w.cylinder(.055,.055,.5,0xa0caf1,0,top+.25,0,g);w.sphere(.09,0xffc568,0,top+.6,0,g,{emissive:0xffb847,emissiveIntensity:.8});}else if(this.cakeTopping===1){for(const s of [-1,1])w.sphere(.15,0xde667f,s*.18,top+.13,0,g);}else{const star=w.mesh(new THREE.OctahedronGeometry(.3),0xf5d67c,0,top+.3,0,g,{metalness:.5,roughness:.3});star.rotation.z=Math.PI/4;}}
 finishCake(){const success=this.cakeLayers===3&&this.cakeFlavor===1&&this.cakeTopping===2;if(!success){this.ui.toast('주문을 다시 살펴보세요: 3단 · 딸기 · 별 장식!');return;}this.ui.reward(45);this.progress.wins++;this.ui.save();this.world.burst(0,2,0,0xffcfdf,40);this.ui.sound('win');this.ui.end('달콤한 주문 완성!','손님이 정말 좋아해요. 45 하트를 받았어요!',()=>this.changeMode('dress'));}
 tick(dt,input){if(this.ended)return;this.time+=dt;this.roundTime+=dt;for(const wing of this.wings)wing.rotation.y=Math.sin(this.time*3)*.25*wing.userData.side;
  if(this.mode==='hearts'){
    const horizontal={x:input.x,z:0,target:input.target?{x:input.target.x,z:0}:null};movePlayer(this.princess,horizontal,dt,6,5);this.princess.position.z=0;this.princess.position.y=.46;this.world.animateCharacter(this.princess,Math.abs(horizontal.x)*6,this.time);this.spawnTimer-=dt;
    if(this.spawnTimer<=0){this.spawnTimer=.5;const bad=Math.random()<.17,mesh=this.world.mesh(new THREE.OctahedronGeometry(bad?.3:.25),bad?0x8b7ac1:0xf487b5,(Math.random()-.5)*10,8,0,this.world.stage,{emissive:bad?0x4e4075:0xbf5d87,emissiveIntensity:.2});if(!bad){this.world.sphere(.18,0xf487b5,-.13,.13,0,mesh);this.world.sphere(.18,0xf487b5,.13,.13,0,mesh);}this.hearts.push({mesh,bad});}
    this.hearts=this.hearts.filter(h=>{h.mesh.position.y-=dt*(2.3+this.config.difficulty*.5);h.mesh.rotation.y+=dt*2;if(h.mesh.position.y<1.6&&h.mesh.position.y>.5&&Math.abs(h.mesh.position.x-this.princess.position.x)<.7){if(h.bad){this.caught=Math.max(0,this.caught-2);this.ui.sound('hit');}else{this.caught++;this.ui.sound('coin');this.world.burst(h.mesh.position.x,1,0,0xffc7dd,7);}this.world.remove(h.mesh);return false;}if(h.mesh.position.y<.1){if(!h.bad)this.missed++;this.world.remove(h.mesh);return false;}return true;});
    if(this.roundTime>=45){this.ended=true;this.ui.reward(this.caught*3);this.ui.end('하트 캐치 완료!',`${this.caught}개의 하트를 받았어요! ${this.caught*3} 하트 선물!`,()=>this.changeMode('dress'));}
  }else if(this.mode==='cake'){if(this.cake)this.cake.rotation.y+=dt*.2;}
  else if(this.runway){this.runway+=dt;const t=this.runway;if(t<3){this.princess.position.z=t/3*8;this.princess.rotation.y=0;this.world.animateCharacter(this.princess,2.7,this.time);}else if(t<5){this.princess.rotation.y=(t-3)*Math.PI;this.princess.userData.leftArm.rotation.z=.6;this.princess.userData.rightArm.rotation.z=-.6;}else if(t<8){this.princess.position.z=8-(t-5)/3*8;this.princess.rotation.y=Math.PI;this.world.animateCharacter(this.princess,2.7,this.time);}else{this.runway=0;this.princess.position.z=0;this.princess.rotation.y=0;this.princess.userData.leftArm.rotation.z=0;this.princess.userData.rightArm.rotation.z=0;this.runwayComplete();this.world.orbit(0,1,0,13);}}
  else{if(this.twirlTime>0){this.twirlTime-=dt;this.princess.rotation.y+=dt*5;this.princess.userData.dress.rotation.y-=dt*1.5;}else this.princess.rotation.y=Math.sin(this.time*.4)*.18;this.princess.userData.leftArm.rotation.z=Math.sin(this.time*2)*.05;this.princess.userData.rightArm.rotation.z=-Math.sin(this.time*2)*.05;}
  if(this.pet){this.pet.position.lerp(this.princess.position.clone().add(new THREE.Vector3(1.5,0,.5)),Math.min(1,dt*5));this.pet.position.y=.46+Math.abs(Math.sin(this.time*5))*.13;this.pet.rotation.y=this.princess.rotation.y;}this.hud();
 }
 hud(){this.ui.stats([{label:'내 하트',value:this.progress.coins},{label:this.mode==='hearts'?'남은 시간':'최고 패션 점수',value:this.mode==='hearts'?Math.max(0,Math.ceil(45-this.roundTime))+'초':this.progress.best+'점'},{label:this.mode==='hearts'?'받은 하트':'드레스',value:this.mode==='hearts'?this.caught:STYLES[this.outfit.style]},{label:'스튜디오',value:{dress:'옷장',show:'패션쇼',hearts:'하트 캐치',cake:'케이크 공방'}[this.mode]}]);}
 pick(action,point){if(this.mode==='hearts')this.ui.input.target={x:clamp(point.x,-5,5),z:0};else this.twirl();}
}
