import {World} from './world.js';
import {GAME_INFO,safeProgress,clamp} from './rules.js';
const $=id=>document.getElementById(id),id=document.body.dataset.game,info=GAME_INFO[id];
const read=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))??fallback;}catch{return fallback;}};
const write=(key,value)=>{try{localStorage.setItem(key,JSON.stringify(value));return true;}catch{return false;}};
const profiles=['준우','은우','리우','아빠','손님'];let profile=read('junwoo-3d-profile','준우');if(!profiles.includes(profile))profile='준우';
let progress=safeProgress(read('junwoo-3d-'+id+'-'+profile,{})),config={difficulty:clamp(Math.floor(Number(read('junwoo-3d-difficulty',1))||0),0,2)},world,game,GameClass,paused=true,started=false,muted=read('junwoo-3d-muted',false),low=read('junwoo-3d-low',false),last=0,toastTimer,audioCtx=null,saveTimer=0,statsKey='',confirmCallback=null;
const keys=new Set(),input={x:0,z:0,target:null},joy={x:0,z:0};
if(!info)throw Error('알 수 없는 게임');
document.title=info.title+' · 준우네 게임천국';document.documentElement.style.setProperty('--accent',info.color);$('gameTitle').textContent=info.title;$('gameSubtitle').textContent=info.subtitle;$('welcomeTitle').textContent=info.title;$('welcomeText').textContent=info.goal;$('controlsHint').textContent=info.hint;$('legacyLink').href='./'+info.legacy;$('errorLegacy').href='./'+info.legacy;$('profile').value=profile;$('difficulty').value=String(config.difficulty);
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,3200);}
function sound(type){if(muted)return;try{audioCtx??=new(window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const tones={coin:[660,880],hit:[170],jump:[330,490],win:[523,659,784],build:[440,660]}[type]||[440];tones.forEach((freq,i)=>{const osc=audioCtx.createOscillator(),gain=audioCtx.createGain(),t=audioCtx.currentTime+i*.07;osc.type='sine';osc.frequency.value=freq;gain.gain.setValueAtTime(.05,t);gain.gain.exponentialRampToValueAtTime(.001,t+.12);osc.connect(gain);gain.connect(audioCtx.destination);osc.start(t);osc.stop(t+.13);});}catch{}}
function save(){if(!write('junwoo-3d-'+id+'-'+profile,progress)&&!save.warned){save.warned=true;toast('저장 공간을 사용할 수 없어요. 이번 기록은 자동 저장되지 않을 수 있어요.');}}
function stopInput(){keys.clear();joy.x=joy.z=input.x=input.z=0;input.target=null;$('joyKnob').style.transform='translate(0,0)';}
function setPaused(value){paused=value;stopInput();$('pauseBtn').textContent=value?'▶ 계속':'Ⅱ 쉬기';$('pauseCover').hidden=!value||!started;$('welcome').hidden=started;save();}
function closeDialog(){confirmCallback=null;$('dialog').close();}
function modal(title,message,actions=[]){$('dialogTitle').textContent=title;$('dialogText').textContent=message;$('dialogActions').replaceChildren();for(const action of actions){const b=document.createElement('button');b.textContent=action.label;if(action.primary)b.className='primary';b.onclick=()=>{closeDialog();action.click?.();};$('dialogActions').append(b);}if(!$('dialog').open)$('dialog').showModal();}
function resume(){if(game?.ended){ui.end('이번 모험이 끝났어요.','다시 시작해서 새로운 기록에 도전하세요.',()=>game.reset());return;}started=true;setPaused(false);sound('coin');}
const ui={input,
 movement:enabled=>{$('joystick').hidden=!enabled;},
 panel:open=>{if(open&&!document.body.classList.contains('panel-open'))ui.panelAt=performance.now();document.body.classList.toggle('panel-open',!!open);$('panelBtn').setAttribute('aria-expanded',String(!!open));},
 goal:text=>{$('goal').textContent=text;},toast,sound,save,
 stats:items=>{const key=JSON.stringify(items);if(key===statsKey)return;statsKey=key;$('stats').replaceChildren(...items.map(item=>{const div=document.createElement('div');const label=document.createElement('span'),value=document.createElement('strong');label.textContent=item.label;value.textContent=String(item.value);div.append(label,value);return div;}));},
 controls:(title,items)=>{$('panelTitle').textContent=title;const fragment=document.createDocumentFragment();for(const item of items){if(item.text){const p=document.createElement('p');p.className='panel-note';p.textContent=item.text;fragment.append(p);}else if(item.options){const label=document.createElement('label');label.textContent=item.label;const select=document.createElement('select');for(const [value,name] of item.options){const o=document.createElement('option');o.value=value;o.textContent=name;select.append(o);}select.value=item.value;select.onchange=()=>item.change(select.value);label.append(select);fragment.append(label);}else{const button=document.createElement('button');button.className='control-card';button.disabled=!!item.disabled;const span=document.createElement('span');span.textContent=item.label;button.append(span);if(item.small){const small=document.createElement('small');small.textContent=item.small;button.append(small);}button.onclick=()=>{if(game?.ended)return;item.click?.();};fragment.append(button);}}$('panelContent').replaceChildren(fragment);},
 actionMap:new Map(),actions:items=>{ui.actionMap.clear();$('actions').replaceChildren();for(const item of items){ui.actionMap.set(item.key,item.action);const button=document.createElement('button');const key=document.createElement('kbd'),label=document.createElement('span');key.textContent=item.key==='Space'?'SPACE':item.key.replace('Key','');label.textContent=item.label;button.append(key,label);button.onpointerdown=e=>{e.preventDefault();if(!paused) item.action();};$('actions').append(button);}},
 spend:amount=>{if(progress.coins<amount){toast('코인이 부족해요. 모험을 통해 더 모아 보세요.');return false;}progress.coins-=amount;save();sound('build');return true;},
 reward:(amount,notify=true)=>{progress.coins=clamp(progress.coins+Math.max(0,Math.floor(amount)),0,1e9);save();if(notify)toast(`+${Math.floor(amount)} ${id==='princess'?'하트':'코인'}!`);},
 confirm:(title,text,callback)=>{const wasPaused=paused;setPaused(true);confirmCallback=()=>setPaused(wasPaused);modal(title,text,[{label:'취소',click:()=>setPaused(wasPaused)},{label:'시작하기',primary:true,click:()=>{callback();setPaused(wasPaused);}}]);},
 end:(title,text,again)=>{setPaused(true);sound('win');modal(title,text,[{label:'다시 도전',primary:true,click:()=>{input.target=null;again();setPaused(false);}},{label:'게임천국',click:()=>location.assign('https://coolgary825.github.io/mini-games/')}]);}
};
$('startBtn').onclick=resume;$('resumeBtn').onclick=resume;$('pauseBtn').onclick=()=>{if(!started)resume();else setPaused(!paused);};
$('restartBtn').onclick=()=>ui.confirm('처음부터 다시 시작할까요?','3D 모험에서 모은 코인과 꾸미기는 보관돼요.',()=>{progress.run=null;game.reset();});
$('profile').onchange=()=>{save();stopInput();profile=$('profile').value;write('junwoo-3d-profile',profile);progress=safeProgress(read('junwoo-3d-'+id+'-'+profile,{}));game=new GameClass(world,ui,progress,config);started=false;setPaused(true);toast(profile+'의 3D 모험을 열었어요.');};
$('difficulty').onchange=()=>{const next=Number($('difficulty').value),old=config.difficulty;ui.confirm('난이도를 바꿔 시작할까요?','현재 라운드를 다시 시작해요. 모은 코인은 보관돼요.',()=>{config.difficulty=next;write('junwoo-3d-difficulty',next);progress.run=null;game.reset();});$('difficulty').value=String(old);const restore=confirmCallback;confirmCallback=()=>{restore?.();$('difficulty').value=String(old);};const buttons=$('dialogActions').querySelectorAll('button');buttons[1]?.addEventListener('click',()=>$('difficulty').value=String(config.difficulty));};
$('soundBtn').onclick=()=>{muted=!muted;write('junwoo-3d-muted',muted);$('soundBtn').textContent=muted?'♪ 소리 꺼짐':'♪ 소리 켜짐';if(!muted)sound('coin');};$('soundBtn').textContent=muted?'♪ 소리 꺼짐':'♪ 소리 켜짐';
$('qualityBtn').onclick=()=>{low=!low;write('junwoo-3d-low',low);if(world?.renderer){world.renderer.setPixelRatio(low?1:Math.min(devicePixelRatio||1,1.5));world.renderer.shadowMap.enabled=!low;world.resize();}$('qualityBtn').textContent=low?'화질: 가볍게':'화질: 선명하게';};$('qualityBtn').textContent=low?'화질: 가볍게':'화질: 선명하게';
$('fullscreenBtn').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if(document.documentElement.requestFullscreen)await document.documentElement.requestFullscreen();else toast('홈 화면에 추가하면 더 넓게 즐길 수 있어요.');}catch{toast('전체 화면을 사용할 수 없는 브라우저예요.');}};
document.querySelector('.sidepanel').addEventListener('click',e=>{if(ui.panelAt&&performance.now()-ui.panelAt<450){e.preventDefault();e.stopPropagation();}},true);
$('panelBtn').onclick=()=>{document.body.classList.toggle('panel-open');$('panelBtn').setAttribute('aria-expanded',String(document.body.classList.contains('panel-open')));};$('closePanel').onclick=()=>{document.body.classList.remove('panel-open');$('panelBtn').setAttribute('aria-expanded','false');};
$('helpBtn').onclick=()=>{setPaused(true);modal(info.subtitle+' 조작 안내',info.hint+'\n\n'+info.goal+'\n\n휴대폰은 왼쪽 조이스틱과 오른쪽 행동 버튼을 사용하세요. 바닥을 누르면 그곳으로 걸어가요. 디펜스와 공주게임은 드래그로 카메라를 회전할 수 있어요.\n\n난이도 3단계, 가족별 코인·꾸미기·최고 기록을 이 기기에 자동 저장해요. 3D 모험의 진행은 새롭게 시작하며, 원래 게임의 저장 기록은 ‘기존 게임 이어하기’에서 그대로 이어갈 수 있어요.\n\n움직임이 느리면 ‘화질: 가볍게’를 선택해 보세요.',[{label:'계속하기',primary:true,click:resume}]);};
$('closeDialog').onclick=()=>{const callback=confirmCallback;closeDialog();callback?.();};$('dialog').addEventListener('cancel',()=>{const callback=confirmCallback;confirmCallback=null;callback?.();});
window.addEventListener('keydown',e=>{if(/INPUT|SELECT|TEXTAREA/.test(e.target.tagName)||$('dialog').open)return;if(['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){setPaused(!paused);return;}if(paused)return;if(!e.repeat&&ui.actionMap.has(e.code))ui.actionMap.get(e.code)();keys.add(e.code);if(['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))input.target=null;});window.addEventListener('keyup',e=>keys.delete(e.code));
const joystick=$('joystick');let joyPointer=null;
function joyMove(e){if(e.pointerId!==joyPointer)return;const r=joystick.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,d=Math.hypot(dx,dy),max=38,k=Math.min(1,max/(d||1));joy.x=dx*k/max;joy.z=dy*k/max;input.target=null;$('joyKnob').style.transform=`translate(${dx*k}px,${dy*k}px)`;}
joystick.addEventListener('pointerdown',e=>{if(paused)return;joyPointer=e.pointerId;joystick.setPointerCapture(e.pointerId);joyMove(e);});joystick.addEventListener('pointermove',joyMove);for(const event of ['pointerup','pointercancel','lostpointercapture'])joystick.addEventListener(event,()=>{joyPointer=null;joy.x=joy.z=0;$('joyKnob').style.transform='translate(0,0)';});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&started)setPaused(true);});window.addEventListener('blur',()=>{if(started)setPaused(true);});window.addEventListener('pagehide',save);
function fail(){setPaused(true);$('welcome').hidden=true;$('pauseCover').hidden=true;$('errorCover').hidden=false;$('startBtn').disabled=true;}
async function boot(){try{
 const route={roblox:'roblox',defense:'defense',brainrot:'brainrot','99nights':'nights',princess:'princess'}[id];({Game:GameClass}=await import('./games/'+route+'.js'));world=new World($('scene'),{onPick:(action,point)=>{if(!paused)game?.pick?.(action,point);},onError:fail});game=new GameClass(world,ui,progress,config);if(low){world.renderer.setPixelRatio(1);world.renderer.shadowMap.enabled=false;world.resize();}$('loading').hidden=true;$('startBtn').disabled=false;$('startBtn').textContent=id==='99nights'&&progress.run?.day>1?'이어서 모험하기':'3D 모험 시작';
 function frame(now){requestAnimationFrame(frame);const dt=Math.min(.04,Math.max(0,(now-(last||now))/1000));last=now;if(!document.hidden){if(!paused){input.x=(keys.has('KeyD')||keys.has('ArrowRight')?1:0)-(keys.has('KeyA')||keys.has('ArrowLeft')?1:0)+joy.x;input.z=(keys.has('KeyS')||keys.has('ArrowDown')?1:0)-(keys.has('KeyW')||keys.has('ArrowUp')?1:0)+joy.z;game.tick(dt,input);saveTimer+=dt;if(saveTimer>5){saveTimer=0;save();}}world.update(paused?0:dt);world.render();}}
 requestAnimationFrame(frame);
 }catch(error){console.error('3D game could not start',error);fail();}}
$('joystick').hidden=['defense','princess'].includes(id);
boot();
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
