import assert from 'node:assert/strict';import {fresh,campaign,nextWave,serialize} from '../engine.mjs';import {prepare,fight} from './strategy.mjs';import {CHARACTERS,SAVE_KEY} from '../data.mjs';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');const URL=process.env.MERGE_URL||'http://127.0.0.1:8771/merge-heroes/';const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];
async function open(mobile=false,data=null){const ctx=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1000},isMobile:mobile,hasTouch:mobile,reducedMotion:'reduce'});if(data)await ctx.addInitScript(({key,data})=>localStorage.setItem(key,JSON.stringify(data)),{key:SAVE_KEY,data});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.url()+':'+r.status());});await p.clock.install({time:new Date('2026-10-04T01:00:00Z')});await p.clock.pauseAt(new Date('2026-10-04T01:00:01Z'));await p.goto(URL);await p.locator('#loading').waitFor({state:'hidden'});return p;}
const state=p=>p.evaluate(k=>JSON.parse(localStorage.getItem(k)),SAVE_KEY);
async function click(p,s,touch=false){if(touch)await p.locator(s).tap();else await p.locator(s).click();}
async function select(p,ids,touch=false){await click(p,'#clear',touch);for(const id of ids)await click(p,`[data-unit="${id}"]`,touch);}
async function win(p,touch=false){await click(p,'#start',touch);for(let i=0;i<40&&(await p.locator('body').getAttribute('data-phase'))==='battle';i++)await p.clock.runFor(5000);assert.ok(['reward','won'].includes(await p.locator('body').getAttribute('data-phase')));assert.equal(await p.locator('#result-dialog').isVisible(),true);}
function fixture(wave){const g=fresh();for(let i=1;i<wave;i++){prepare(g);fight(g);nextWave(g);}prepare(g);g.speed=2;return campaign(g);}
try{const p=await open();await p.evaluate(()=>localStorage.setItem('junwoo-mix-heroes-v1','old-game-record'));await click(p,'#codex');assert.equal(await p.locator('.codex-card[data-unlocked="true"]').count(),1);assert.equal(await p.locator('.codex-card.locked [data-stat]').count(),0);assert.equal(await p.locator('[data-codex="melee-1"] [data-stat="hp"]').textContent(),'180');assert.equal(await p.locator('[data-codex="melee-1"] [data-stat="power"]').textContent(),'20');await click(p,'#codex-dialog [data-close]');
await click(p,'[data-buy="melee"]');assert.equal((await state(p)).coins,130);await select(p,[1,2]);assert.match(await p.locator('#merge-info').textContent(),/가을/);await click(p,'#merge');let g=await state(p);assert.equal(g.units.length,1);assert.equal(g.units[0].tier,2);assert.equal(g.coins,130);assert.ok(g.discovered.includes('melee-1'));assert.ok(g.discovered.includes('melee-2'));await click(p,'#codex');assert.equal(await p.locator('[data-gembuy="melee-2"]').isDisabled(),true);assert.match(await p.locator('[data-gembuy="melee-2"]').textContent(),/25/);await click(p,'#codex-dialog [data-close]');
await click(p,'#start');await p.clock.runFor(5000);await click(p,'#codex');assert.equal(await p.locator('body').getAttribute('data-phase'),'paused');assert.equal(await p.locator('[data-gembuy="melee-1"]').isDisabled(),true);await click(p,'#codex-dialog [data-close]');await click(p,'#start');for(let i=0;i<20&&(await p.locator('body').getAttribute('data-phase'))==='battle';i++)await p.clock.runFor(5000);assert.equal(await p.locator('body').getAttribute('data-phase'),'reward');assert.equal((await state(p)).gems,30);const coins=(await state(p)).coins;await p.reload();await p.locator('#loading').waitFor({state:'hidden'});assert.equal((await state(p)).gems,30);assert.equal((await state(p)).coins,coins);await click(p,'#result-action');await click(p,'#codex');await click(p,'[data-gembuy="melee-2"]');g=await state(p);assert.equal(g.gems,5);assert.equal(g.coins,coins);assert.equal(g.units.length,2);assert.match(await p.locator('#codex-status').textContent(),/가을/);await click(p,'#codex-dialog [data-close]');await select(p,g.units.map(u=>u.id));await click(p,'#merge');g=await state(p);assert.equal(g.units[0].tier,3);assert.equal(g.discovered.length,3);await click(p,'#codex');assert.equal(await p.locator('[data-codex="melee-3"] [data-stat="hp"]').textContent(),CHARACTERS['melee-3'].hp.toLocaleString());assert.equal(await p.locator('[data-codex="melee-3"] [data-stat="power"]').textContent(),String(CHARACTERS['melee-3'].power));await p.screenshot({path:'/tmp/merge-codex-discovered.png'});await click(p,'#codex-dialog [data-close]');assert.equal(await p.evaluate(()=>localStorage.getItem('junwoo-mix-heroes-v1')),'old-game-record');console.log('PASS desktop purchase, normal merge, permanent codex, real stats, victory gems, gem purchase, reload, old saves');
await click(p,'#restart');await click(p,'#confirm-action');g=await state(p);assert.equal(g.coins,180);assert.equal(g.gems,20);assert.equal(g.discovered.length,3);console.log('PASS new adventure retains collected characters');
const m=await open(true);await click(m,'[data-buy="ranged"]',true);await select(m,[1,2],true);assert.equal(await m.locator('#merge').isDisabled(),true);await click(m,'[data-mode="super"]',true);assert.match(await m.locator('#merge').textContent(),/80/);assert.match(await m.locator('#merge-info').textContent(),/가을/);await m.screenshot({path:'/tmp/merge-super-mobile.png',fullPage:true});await click(m,'#merge',true);g=await state(m);assert.equal(g.coins,40);assert.equal(g.units.length,1);assert.equal(g.units[0].type,'melee');assert.equal(g.units[0].tier,2);assert.ok(g.discovered.includes('ranged-1'));await click(m,'#codex-mobile',true);await click(m,'[data-filter="ranged"]',true);assert.equal(await m.locator('.codex-card').count(),5);assert.equal(await m.locator('.codex-card[data-unlocked="true"]').count(),1);await click(m,'[data-gembuy="ranged-1"]',true);g=await state(m);assert.equal(g.gems,10);assert.equal(g.coins,40);await click(m,'#codex-dialog [data-close]',true);await select(m,g.units.map(u=>u.id),true);assert.equal(await m.locator('#merge').isDisabled(),true);assert.match(await m.locator('#merge').textContent(),/부족/);await win(m,true);assert.equal((await state(m)).gems,20);await click(m,'#result-action',true);console.log('PASS touch cross-role super merge, exact cost, codex repurchase, insufficient funds, victory gems');
for(const width of [320,390,768]){await m.setViewportSize({width,height:844});assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,`overflow ${width}`);}console.log('PASS mobile layouts');
for(const wave of [5,10,20]){const q=await open(wave===20,fixture(wave));assert.equal(await q.locator('body').getAttribute('data-wave'),String(wave));await win(q,wave===20);console.log('PASS browser boss wave',wave);if(wave===20){assert.equal(await q.locator('body').getAttribute('data-phase'),'won');await click(q,'#result-action',true);await click(q,'#codex-mobile',true);assert.equal(await q.locator('.codex-card[data-unlocked="true"]').count(),10);const before=await state(q);await click(q,'[data-gembuy="ranged-5"]',true);const after=await state(q);assert.equal(after.gems,before.gems-320);assert.equal(after.coins,before.coins);await q.screenshot({path:'/tmp/merge-complete-codex.png'});console.log('PASS all 10 entries and highest tier gem purchase after final victory');}await q.context().close();}
const corrupt=await open(false,{...fresh(),gems:-2});assert.equal((await state(corrupt)).gems,20);const ctx=await browser.newContext();await ctx.addInitScript(()=>{Storage.prototype.setItem=()=>{throw Error('disabled')};Storage.prototype.getItem=()=>{throw Error('disabled')};});const bp=await ctx.newPage();await bp.goto(URL);await bp.locator('#loading').waitFor({state:'hidden'});await bp.locator('[data-buy="ranged"]').click();assert.equal(await bp.locator('#coins').textContent(),'120');assert.match(await bp.locator('#save-status').textContent(),/저장이 제한/);assert.deepEqual(errors,[]);console.log('PASS corrupt/disabled storage and zero missing assets or browser errors');}finally{await browser.close();}
