import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,buy,start,step,cast,pause,retry,nextWave,serialize,restore,autoDeploy} from '../engine.mjs';
import {WAVES,CHARACTERS,stats,clone} from '../data.mjs';import {prepare,fight} from './strategy.mjs';
function combat(type='melee',tier=3){const g=fresh();g.units=[{id:1,type,tier,slot:4}];start(g);g.run.spawned=999;g.run.spawnIn=999;g.run.energy=100;g.run.units[0].cd=0;return g;}
const enemy=(id,type='slime',x=440,y=335)=>({id,type,x,y,hp:100000,maxHp:100000,cd:999,anim:0,flash:0,specialIn:999,stun:0,slow:0,charge:null});
test('skills spend battle energy only; cooldown and energy failures are atomic; pause stops recharge',()=>{const g=combat();g.run.enemies=[enemy(1)];const coins=g.coins,gems=g.gems;assert.equal(cast(g,'overdrive').ok,true);assert.equal(g.run.energy,60);assert.equal(g.run.overdrive,5);const before=clone(g);assert.equal(cast(g,'overdrive').ok,false);assert.equal(cast(g,'bad').ok,false);assert.deepEqual(g,before);pause(g);step(g,1);assert.equal(g.run.energy,60);assert.equal(cast(g,'pulse').ok,false);pause(g);g.run.energy=54;const low=clone(g);assert.equal(cast(g,'pulse').ok,false);assert.deepEqual(g,low);assert.equal(g.coins,coins);assert.equal(g.gems,gems);});
test('overdrive actually delivers more attacks in five seconds',()=>{function hits(skill){const g=combat();g.run.enemies=[enemy(1)];if(skill)cast(g,'overdrive');for(let i=0;i<150;i++)step(g,1/30);return 100000-g.run.enemies[0].hp;}assert.ok(hits(true)>hits(false)*1.5);});
test('boss telegraphs before damage and a pulse cancels the attack and stuns',()=>{const g=combat();g.wave=5;const e=enemy(1,'boss');e.specialIn=0;g.run.enemies=[e];g.run.units[0].cd=999;const hp=g.run.units[0].hp;step(g,.1);assert.ok(e.charge);assert.equal(g.run.units[0].hp,hp);assert.equal(cast(g,'pulse').ok,true);assert.equal(e.charge,null);assert.equal(e.stun,2);assert.equal(g.run.interrupts,1);assert.ok(e.hp<e.maxHp);for(let i=0;i<20;i++)step(g,.1);assert.equal(g.run.units[0].hp,hp);});
test('ignored boss warning damages units in its area after the countdown',()=>{const g=combat();g.wave=5;const e=enemy(1,'boss');e.specialIn=0;g.run.enemies=[e];g.run.units[0].cd=999;const hp=g.run.units[0].hp;for(let i=0;i<20;i++)step(g,.1);assert.ok(g.run.units[0].hp<hp);assert.equal(e.charge,null);});
test('artillery sends projectiles and hurts heroes while remaining at range',()=>{const g=combat();const e=enemy(1,'artillery',740);e.cd=0;g.run.enemies=[e];const hp=g.run.units[0].hp;step(g,.1);assert.ok(g.run.hostile.length);for(let i=0;i<15;i++)step(g,.1);assert.ok(g.run.units[0].hp<hp);});
test('shield enemies reduce ranged damage while basic enemies match codex damage',()=>{function damage(type){const g=combat('ranged',1);g.run.enemies=[enemy(1,type)];step(g,.01);g.run.units[0].cd=999;for(let i=0;i<10;i++)step(g,.05);return 100000-g.run.enemies[0].hp;}assert.equal(damage('slime'),CHARACTERS['ranged-1'].power);assert.equal(damage('tank'),Math.round(CHARACTERS['ranged-1'].power*.55));});
test('three-star melee cleaves every fourth attack; missiles damage and slow a nearby enemy',()=>{const g=combat();g.run.enemies=[enemy(1),enemy(2,'slime',480)];g.run.units[0].attacks=3;step(g,.01);assert.ok(g.run.enemies[1].hp<100000);const r=combat('ranged',4);r.run.enemies=[enemy(1),enemy(2,'slime',480)];step(r,.01);r.run.units[0].cd=999;for(let i=0;i<10;i++)step(r,.05);assert.ok(r.run.enemies[0].slow>0);assert.ok(r.run.enemies[1].hp<100000);});
test('recommended deployment uses six strongest heroes and preserves ownership and roles',()=>{const g=fresh();g.coins=1000;while(g.units.length<8)buy(g,g.units.length%2?'ranged':'melee');g.units[7].tier=5;const before=g.units.map(u=>[u.id,u.type,u.tier]);assert.equal(autoDeploy(g).ok,true);assert.notEqual(g.units[7].slot,null);assert.equal(g.units.filter(u=>u.slot!==null).length,6);assert.equal(new Set(g.units.filter(u=>u.slot!==null).map(u=>u.slot)).size,6);assert.deepEqual(g.units.map(u=>[u.id,u.type,u.tier]),before);start(g);assert.equal(autoDeploy(g).ok,false);});
test('medals and result rating survive reload, cannot mint resources, and legacy saves get empty medals',()=>{const g=fresh();prepare(g);fight(g);assert.ok(g.run.stars>=1&&g.run.stars<=3);assert.equal(g.medals[0],g.run.stars);const loaded=restore(serialize(g));assert.deepEqual(loaded.medals,g.medals);assert.equal(loaded.run.stars,g.run.stars);const before=serialize(loaded);step(loaded,1);assert.equal(serialize(loaded),before);const old=JSON.parse(serialize(g));delete old.medals;assert.deepEqual(restore(JSON.stringify(old)).medals,Array(20).fill(0));});
test('late-game idle army loses; spending gems and using skills clears the same campaign',()=>{let idle=fresh();for(let w=1;w<=20;w++){prepare(idle);fight(idle,false);if(idle.phase==='lost')break;nextWave(idle);}assert.equal(idle.phase,'lost');const g=fresh();for(let w=1;w<=20;w++){prepare(g);fight(g);assert.equal(g.phase,w===20?'won':'reward');if(w<20)nextWave(g);}assert.ok(g.run.skillUses>0);assert.ok(g.run.interrupts>0);assert.ok(g.medals.reduce((a,b)=>a+b,0)<60,'a win alone must not hand out every medal');});
test('loss and reload restore currencies, army and medals rather than battle skill energy',()=>{const g=fresh();prepare(g);const before=serialize(g);start(g);step(g,1/30);g.run.energy=0;g.crystal=0;step(g,.1);assert.equal(g.phase,'lost');assert.equal(serialize(restore(serialize(g))),before);retry(g);start(g);assert.equal(g.run.energy,50);});
