import {HEROES,WEAPONS,ENEMIES,WAVES,SLOTS,recipe,clone} from './data.mjs';
export function fresh(){return {version:1,wave:1,phase:'prep',coins:145,crystal:100,units:[{id:1,type:'melee',slot:4,weapon:'sword'}],bag:[{id:2,kind:'sword'},{id:3,kind:'staff'}],nextId:4,tutorial:0,muted:true,speed:1,checkpoint:null,run:null};}
export function canEdit(g){return g.phase==='prep';}
function fail(message){return {ok:false,message};}function ok(message,extra={}){return {ok:true,message,...extra};}
export function buyHero(g,type){if(!canEdit(g))return fail('전투가 끝나면 친구를 부를 수 있어요.');const d=HEROES[type];if(!d)return fail('친구를 골라 주세요.');if(g.units.length>=6)return fail('여섯 자리가 모두 찼어요.');if(g.coins<d.cost)return fail(`코인이 ${d.cost-g.coins}개 더 필요해요.`);const order=type==='melee'?[4,3,5,1,0,2]:[1,0,2,4,3,5],slot=order.find(n=>!g.units.some(u=>u.slot===n));const u={id:g.nextId++,type,slot,weapon:type==='melee'?'sword':'bow'};g.coins-=d.cost;g.units.push(u);g.tutorial=Math.max(1,g.tutorial);return ok(`${d.name} 등장! 기본 무기도 함께 왔어요.`,{id:u.id});}
export function buyWeapon(g,kind){if(!canEdit(g))return fail('전투가 끝나면 무기를 살 수 있어요.');if(!WEAPONS[kind]?.base)return fail('기본 무기를 골라 주세요.');if(g.bag.length>=20)return fail('가방이 가득해요. 합성하거나 장착해 보세요.');if(g.coins<20)return fail(`코인이 ${20-g.coins}개 더 필요해요.`);g.coins-=20;const id=g.nextId++;g.bag.push({id,kind});return ok(`${WEAPONS[kind].name}을 가방에 넣었어요.`,{id});}
export function moveHero(g,id,slot){if(!canEdit(g))return fail('배치는 준비 시간에 바꿀 수 있어요.');const u=g.units.find(u=>u.id===id);if(!u||!SLOTS[slot])return fail('친구와 자리를 골라 주세요.');const other=g.units.find(x=>x.slot===slot);if(other)other.slot=u.slot;u.slot=slot;return ok('자리를 바꿨어요.');}
export function mix(g,ids){if(!canEdit(g))return fail('전투가 끝나면 합성할 수 있어요.');if(ids.length!==2||ids[0]===ids[1])return fail('무기 두 개를 골라 주세요.');const items=ids.map(id=>g.bag.find(i=>i.id===id));if(items.some(x=>!x))return fail('가방에 있는 무기를 골라 주세요.');const result=recipe(items[0].kind,items[1].kind);if(!result)return fail('이 조합은 아직 없어요. 조합 책을 살펴보세요.');g.bag=g.bag.filter(i=>!ids.includes(i.id));const id=g.nextId++;g.bag.push({id,kind:result});g.tutorial=Math.max(2,g.tutorial);return ok(`${WEAPONS[result].name} 완성! 친구에게 장착해 주세요.`,{id,kind:result});}
export function equip(g,uid,itemId){if(!canEdit(g))return fail('전투가 끝나면 무기를 바꿀 수 있어요.');const u=g.units.find(x=>x.id===uid),item=g.bag.find(x=>x.id===itemId);if(!u||!item)return fail('친구와 무기 하나를 골라 주세요.');if(WEAPONS[item.kind].role!==u.type)return fail(`${WEAPONS[item.kind].name}은 ${HEROES[WEAPONS[item.kind].role].name} 전용이에요.`);const before=u.weapon;u.weapon=item.kind;item.kind=before;if(!WEAPONS[u.weapon].base)g.tutorial=Math.max(3,g.tutorial);return ok(`${HEROES[u.type].name}에게 ${WEAPONS[u.weapon].name} 장착!`);}
export function campaign(g){const {checkpoint,run,...data}=g;return clone(data);}
export function start(g){if(g.phase!=='prep'||!g.units.length)return fail('친구를 먼저 불러 주세요.');g.checkpoint=campaign(g);g.phase='battle';g.tutorial=4;g.run={time:0,spawned:0,kills:0,earned:0,spawnIn:1.2,enemies:[],shots:[],fx:[],nextEnemy:1,events:[],units:g.units.map(u=>({...u,x:SLOTS[u.slot].x,y:SLOTS[u.slot].y,hp:HEROES[u.type].hp,maxHp:HEROES[u.type].hp,cd:.2,anim:0,target:null})),reward:0};return ok('보석을 지켜 주세요!');}
export function pause(g){if(g.phase==='battle'){g.phase='paused';return true;}if(g.phase==='paused'){g.phase='battle';return true;}return false;}
export function retry(g){if(!g.checkpoint||!['lost','battle','paused'].includes(g.phase))return false;const muted=g.muted,speed=g.speed,cp=clone(g.checkpoint);Object.assign(g,cp,{muted,speed,phase:'prep',checkpoint:null,run:null});return true;}
export function nextWave(g){if(g.phase!=='reward'||g.wave>=10)return false;g.wave++;g.phase='prep';g.crystal=100;g.run=null;g.checkpoint=null;return true;}
function dist(a,b){return Math.hypot(a.x-b.x,a.y-b.y);}
function move(a,b,speed,dt,stop=0){const d=dist(a,b);if(d<=stop)return;const k=Math.min(speed*dt,d-stop)/d;a.x+=(b.x-a.x)*k;a.y+=(b.y-a.y)*k;}
function effect(r,kind,x,y,color,text=''){r.fx.push({kind,x,y,color,text,life:kind==='text'?1:.45,max:kind==='text'?1:.45});}
function hit(g,e,amount,kind){if(e.hp<=0)return;e.hp-=amount;e.flash=.15;effect(g.run,'text',e.x,e.y-35,kind==='burn'?'#f5915e':'#fff9df',String(Math.round(amount)));if(e.hp<=0){e.hp=0;g.run.kills++;g.run.earned+=ENEMIES[e.type].coins;g.coins+=ENEMIES[e.type].coins;effect(g.run,'burst',e.x,e.y,ENEMIES[e.type].color);effect(g.run,'coin',e.x,e.y-10,'#efc15c');g.run.events.push('pop');}}
function impact(g,e,w){if(e.hp<=0)return;hit(g,e,w.power);if(w.effect==='burn'&&e.hp>0)e.burn=3;if(w.effect==='slow'&&e.hp>0)e.slow=2;if(w.effect==='splash'){effect(g.run,'ring',e.x,e.y,'#b8a0ed');for(const other of g.run.enemies)if(other!==e&&other.hp>0&&dist(other,e)<105)hit(g,other,w.power*.62);}}
function shoot(g,u,e,w){g.run.shots.push({x:u.x+12,y:u.y-24,tx:e.x,ty:e.y-20,target:e.id,kind:u.weapon,speed:430,life:2.5});}
export function step(g,dt){if(g.phase!=='battle')return;const total=Math.min(.15,Math.max(0,dt))*g.speed;let left=total;while(left>0&&g.phase==='battle'){const d=Math.min(1/60,left);tick(g,d);left-=d;}}
function tick(g,dt){const r=g.run,def=WAVES[g.wave-1];r.time+=dt;r.spawnIn-=dt;for(const f of r.fx)f.life-=dt;r.fx=r.fx.filter(f=>f.life>0);if(r.spawned<def.types.length&&r.spawnIn<=0){const type=def.types[r.spawned],d=ENEMIES[type],lane=r.spawned%3;const hp=Math.round(d.hp*def.mult);r.enemies.push({id:r.nextEnemy++,type,x:935,y:[225,335,443][lane],hp,maxHp:hp,cd:.7,burn:0,slow:0,flash:0,anim:0});r.spawned++;r.spawnIn=def.gap;}
 for(const u of r.units){if(u.hp<=0)continue;u.cd-=dt;u.anim=Math.max(0,u.anim-dt);const enemies=r.enemies.filter(e=>e.hp>0);if(!enemies.length){move(u,SLOTS[u.slot],HEROES[u.type].speed,dt,2);continue;}const e=enemies.reduce((a,b)=>dist(u,a)<dist(u,b)?a:b);const data=HEROES[u.type],w=WEAPONS[u.weapon];if(dist(u,e)>data.range){if(u.type==='melee')move(u,e,data.speed,dt,data.range-5);else{const home={x:Math.min(560,SLOTS[u.slot].x+Math.max(0,r.time-7)*8),y:SLOTS[u.slot].y};move(u,home,data.speed,dt,2);}}else if(u.cd<=0){u.cd=data.delay*(w.delay||1);u.anim=.24;u.target=e.id;if(u.type==='melee'){impact(g,e,w);effect(r,'slash',e.x-16,e.y-16,w.color);}else shoot(g,u,e,w);r.events.push('hit');}}
 // A gentle separation keeps individual friends visible while they surround an enemy.
 for(let i=0;i<r.units.length;i++)for(let j=i+1;j<r.units.length;j++){const a=r.units[i],b=r.units[j];if(a.hp<=0||b.hp<=0)continue;let dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy);if(d<38){if(d<.01){dx=0;dy=1;d=1;}const push=(38-d)*Math.min(1,dt*5)*.5;a.x-=dx/d*push;a.y-=dy/d*push;b.x+=dx/d*push;b.y+=dy/d*push;}}
 for(const e of r.enemies){if(e.hp<=0)continue;const d=ENEMIES[e.type];e.flash=Math.max(0,e.flash-dt);e.anim=Math.max(0,e.anim-dt);if(e.burn>0){e.burn-=dt;e.burnTick=(e.burnTick||0)+dt;if(e.burnTick>=.5){e.burnTick-=.5;hit(g,e,3.5,'burn');}}if(e.hp<=0)continue;e.slow=Math.max(0,e.slow-dt);e.cd-=dt;const alive=r.units.filter(u=>u.hp>0);const nearby=alive.length?alive.reduce((a,b)=>dist(e,a)<dist(e,b)?a:b):null;const destination=nearby&&dist(e,nearby)<225?nearby:{x:104,y:335};if(nearby&&destination===nearby&&dist(e,nearby)<49+(e.type==='boss'?20:0)){if(e.cd<=0){nearby.hp=Math.max(0,nearby.hp-d.damage);e.cd=d.delay;e.anim=.24;effect(r,'ring',nearby.x,nearby.y,'#f4b59d');}}else if(dist(e,{x:104,y:335})<=40){if(e.cd<=0){g.crystal=Math.max(0,g.crystal-d.damage);e.cd=d.delay;effect(r,'ring',105,330,'#f49c83');r.events.push('crystal');}}else move(e,destination,d.speed*(e.slow>0?.45:1),dt,30);}
 for(const p of r.shots){p.life-=dt;const e=r.enemies.find(e=>e.id===p.target&&e.hp>0);if(e){p.tx=e.x;p.ty=e.y-20;}const target={x:p.tx,y:p.ty};if(dist(p,target)<p.speed*dt+10){if(e){const w=WEAPONS[p.kind];impact(g,e,w);if(w.effect==='pierce'&&!p.pierced){const other=r.enemies.filter(o=>o!==e&&o.hp>0&&o.x>=e.x-15&&Math.abs(o.y-e.y)<65&&dist(o,e)<210).sort((a,b)=>dist(a,e)-dist(b,e))[0];if(other){p.target=other.id;p.pierced=true;p.life=.8;continue;}}}p.life=0;}else move(p,target,p.speed,dt);}
 r.shots=r.shots.filter(p=>p.life>0);r.enemies=r.enemies.filter(e=>e.hp>0);if(g.crystal<=0){g.phase='lost';r.events.push('lost');return;}if(r.spawned===def.types.length&&r.enemies.length===0){r.reward=38+g.wave*5;g.coins+=r.reward;g.phase=g.wave===10?'won':'reward';r.events.push('win');}}
// Persist the pre-battle checkpoint during combat: reloading can never duplicate rewards.
export function serialize(g){let data=campaign(g);if(['battle','paused','lost'].includes(g.phase)&&g.checkpoint)data={...clone(g.checkpoint),muted:g.muted,speed:g.speed};if(['reward','won'].includes(g.phase))data.lastReward={kills:g.run?.kills??0,earned:g.run?.earned??0,reward:g.run?.reward??0};return JSON.stringify(data);}
export function restore(raw){try{const d=JSON.parse(raw);if(d.version!==1||!Number.isInteger(d.wave)||d.wave<1||d.wave>10||!['prep','reward','won'].includes(d.phase)||!Number.isInteger(d.coins)||d.coins<0||d.coins>100000||!Array.isArray(d.units)||d.units.length<1||d.units.length>6||!Array.isArray(d.bag)||d.bag.length>20||!Number.isInteger(d.nextId)||d.nextId<2||!Number.isFinite(d.crystal)||d.crystal<0||d.crystal>100)throw 0;const ids=new Set(),slots=new Set();for(const u of d.units){if(!HEROES[u.type]||WEAPONS[u.weapon]?.role!==u.type||!Number.isInteger(u.slot)||!SLOTS[u.slot]||slots.has(u.slot)||!Number.isInteger(u.id)||u.id<1||ids.has(u.id))throw 0;ids.add(u.id);slots.add(u.slot);}for(const i of d.bag){if(!WEAPONS[i.kind]||!Number.isInteger(i.id)||i.id<1||ids.has(i.id))throw 0;ids.add(i.id);}if(d.lastReward&&(!['kills','earned','reward'].every(k=>Number.isInteger(d.lastReward[k])&&d.lastReward[k]>=0&&d.lastReward[k]<=100000)))throw 0;if([...ids].some(id=>id>=d.nextId)||(d.phase==='reward'&&d.wave===10)||(d.phase==='won'&&d.wave!==10))throw 0;return {...fresh(),...d,muted:d.muted!==false,speed:d.speed===2?2:1,tutorial:Number.isInteger(d.tutorial)?Math.max(0,Math.min(4,d.tutorial)):0,checkpoint:null,run:d.lastReward?{...d.lastReward,units:[],enemies:[],shots:[],fx:[],time:0,spawned:WAVES[d.wave-1].types.length,events:[]}:null};}catch{return fresh();}}
