import {HEROES,WEAPONS,WAVES,SLOTS,SAVE_KEY,recipe,RECIPES} from './data.mjs';
import {fresh,buyHero,buyWeapon,moveHero,mix,equip,start,pause,retry,nextWave,step,serialize,restore,canEdit} from './engine.mjs';
import {heroArt,weaponArt,icon,enemyArt} from './art.mjs';import {makeRenderer} from './render.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let storageOK=true,g;try{g=restore(localStorage.getItem(SAVE_KEY));}catch{g=fresh();storageOK=false;}
let selected=g.units[0].id,materials=[],lastPhase=g.phase,lastCoins=g.coins,toastTimer,moveMode=false,audio,renderer,previous=0,acc=0;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
function showScreen(screen,scroll=true){if(!['battle','team','forge'].includes(screen))return;document.body.dataset.screen=screen;$$('.quick-nav [data-screen]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.screen===screen)));if(scroll){if(innerWidth<=820)window.scrollTo({top:0,behavior:'instant'});else $({battle:'#battle-area',team:'#team-area',forge:'#forge-area'}[screen]).scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});}}
$$('[data-screen]').forEach(b=>{if(b.tagName==='BUTTON')b.addEventListener('click',()=>showScreen(b.dataset.screen));});
$$('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
function persist(){try{localStorage.setItem(SAVE_KEY,serialize(g));storageOK=true;}catch{storageOK=false;}$('#save-status').textContent=storageOK?'이 기기에 모험을 자동 저장해요':'저장이 제한되어 이번 화면에서만 모험할 수 있어요';}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3500);}
function sound(type){if(g.muted)return;try{audio??=new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();const notes=type==='craft'?[392,523,659,784]:type==='win'?[392,494,587,784]:type==='lost'?[392,330,262]:type==='coin'?[784,1047]:type==='pop'?[520]:[380];notes.forEach((hz,i)=>{const o=audio.createOscillator(),a=audio.createGain(),t=audio.currentTime+i*.09;o.type=type==='pop'?'sine':'triangle';o.frequency.setValueAtTime(hz,t);a.gain.setValueAtTime(.0001,t);a.gain.exponentialRampToValueAtTime(.045,t+.015);a.gain.exponentialRampToValueAtTime(.0001,t+.17);o.connect(a);a.connect(audio.destination);o.start(t);o.stop(t+.18);});}catch{}}
function action(result,tone='coin'){toast(result.message);if(result.ok){persist();sound(tone);}renderUI();return result.ok;}
function chosen(){return g.units.find(u=>u.id===selected)||g.units[0];}
function materialItems(){return materials.map(id=>g.bag.find(i=>i.id===id)).filter(Boolean);}
function renderUI(){const focused=document.activeElement;const focusKey=focused?.id?'#'+focused.id:['item','unit','equipUnit','slot','buyHero','buyWeapon'].map(k=>focused?.dataset?.[k]!==undefined?`[data-${k.replace(/[A-Z]/g,m=>'-'+m.toLowerCase())}="${focused.dataset[k]}"]`:null).find(Boolean);materials=materials.filter(id=>g.bag.some(i=>i.id===id));const u=chosen();selected=u.id;const edit=canEdit(g);document.body.dataset.phase=g.phase;document.body.dataset.wave=g.wave;
$('#coins').textContent=g.coins;if(lastCoins!==g.coins){$('#coins').classList.remove('coin-pop');void $('#coins').offsetWidth;$('#coins').classList.add('coin-pop');lastCoins=g.coins;}
$('#wave-track').innerHTML=WAVES.map((w,i)=>`<li class="${i+1===g.wave?'current':i+1<g.wave?'done':''}" ${i+1===g.wave?'aria-current="step"':''} aria-label="${i+1}단계 ${w.name}${i+1<g.wave?' 완료':''}">${i+1<g.wave?icon('check'):i+1===10?'♛':i+1}</li>`).join('');
$('#wave-badge').textContent=String(g.wave).padStart(2,'0');$('#wave-title').textContent=WAVES[g.wave-1].name;$('#phase-label').textContent={prep:'준비 시간 · 나만의 팀 만들기',battle:'전투 중 · 보석을 지켜 주세요',paused:'잠깐 쉬는 시간',reward:'전투 승리',lost:'다시 도전할 수 있어요',won:'모든 작전 완료'}[g.phase];$('#battle-tip').textContent=WAVES[g.wave-1].tip;
$('#crystal').value=g.crystal;$('#crystal-label').textContent=g.crystal;$('#pause-overlay').hidden=g.phase!=='paused';$('#slot-controls').innerHTML=SLOTS.map((s,i)=>{const unit=g.units.find(u=>u.slot===i);return `<button class="slot-control ${unit?.id===selected?'active':''}" style="left:${s.x/10}%;top:${(s.y-80)/450*100}%" data-slot="${i}" aria-label="${s.row} ${i%3+1}번 자리${unit?' '+HEROES[unit.type].name:' 비어 있음'}" ${!edit?'disabled':''}>${i+1}</button>`;}).join('');
const labels={prep:['play','전투 시작'],battle:['pause','잠깐 멈춤'],paused:['play','이어하기'],reward:['arrow','다음 준비'],lost:['reset','다시 준비'],won:['spark','모험 완료']};const [ic,txt]=labels[g.phase];$('#start').innerHTML=icon(ic)+`<span>${txt}</span>`;$('#speed').textContent=g.speed+'×';$('#speed').setAttribute('aria-label',`전투 속도 ${g.speed===1?2:1}배로 변경`);$('#sound').innerHTML=icon(g.muted?'mute':'sound');$('#sound').setAttribute('aria-label',g.muted?'소리 켜기':'소리 끄기');$('#sound').setAttribute('aria-pressed',String(!g.muted));
$('#hero-shop').innerHTML=Object.entries(HEROES).map(([key,h])=>`<article class="hero-card ${key}"><div class="portrait">${heroArt(key)}</div><div><h3>${h.name}<span class="role">${h.role}</span></h3><p>${h.hint}</p><div class="mini-stats"><span>♥ 체력 ${h.hp}</span><span>기본 무기 포함</span></div></div><button class="buy-hero" data-buy-hero="${key}" ${!edit||g.coins<h.cost||g.units.length>=6?'disabled':''} aria-label="${h.name} 구매 ${h.cost} 코인"><span>${g.units.length>=6?'팀 완성!':!edit?'전투 중':g.coins<h.cost?'코인 부족':'모집'}</span><b>${icon('coin')}${h.cost}</b></button></article>`).join('');
$('#team-count').textContent=`${g.units.length} / 6명`;$('#roster').innerHTML=g.units.map((u,i)=>`<button class="roster-hero ${u.id===selected?'selected':''}" data-unit="${u.id}" aria-pressed="${u.id===selected}" aria-label="${i+1}번 ${HEROES[u.type].name}, ${WEAPONS[u.weapon].name}, ${SLOTS[u.slot].row}">${heroArt(u.type)}<span>${HEROES[u.type].name} ${i+1}</span></button>`).join('');$('#hero-detail').innerHTML=`<div><b>${HEROES[u.type].name}</b> · ${WEAPONS[u.weapon].name} · 공격 힘 ${WEAPONS[u.weapon].power} <span>— ${edit?'무기 하나를 고르면 장착할 수 있어요.':'친구가 쓰러져도 다음 전투에 돌아와요.'}</span></div>${edit?`<button class="move-button ${moveMode?'active':''}" id="move-hero">${moveMode?'이동할 자리 선택':'자리 옮기기'}</button>`:''}`;
$('#forge-targets').innerHTML=g.units.map((hero,i)=>`<button class="equip-target ${hero.id===selected?'selected':''}" data-equip-unit="${hero.id}" aria-pressed="${hero.id===selected}">${heroArt(hero.type)}<span>${HEROES[hero.type].name} ${i+1}</span></button>`).join('');
const mi=materialItems(),result=mi.length===2?recipe(mi[0].kind,mi[1].kind):null;
document.body.dataset.materials=String(mi.length);$('#mix-preview').innerHTML=`<div class="mix-slot ${mi[0]?'filled':''}">${mi[0]?weaponArt(mi[0].kind):'?'}</div><span class="mix-operator">+</span><div class="mix-slot ${mi[1]?'filled':''}">${mi[1]?weaponArt(mi[1].kind):'?'}</div><span class="mix-operator">→</span><div class="mix-slot result ${result?'filled':''}">${result?weaponArt(result):icon('spark')}</div>`;
$('#mix-info').innerHTML=result?`<b>${WEAPONS[result].name} · ${HEROES[WEAPONS[result].role].name} 전용</b><p>${WEAPONS[result].desc}</p>`:mi.length===2?'<b>다른 재료를 섞어 볼까요?</b><p>조합 책에서 어울리는 무기를 찾아요.</p>':'<b>어떤 무기가 탄생할까요?</b><p>가방에서 기본 무기 두 개를 골라 보세요.</p>';
$('#craft').disabled=!edit||!result;$('#craft').innerHTML=icon('spark')+`<span>${!edit?'전투가 끝나면 합성할 수 있어요':result?'합성하기':'무기 2개를 골라 주세요'}</span>`;
$('#bag-count').textContent=g.bag.length+'/20';$('#inventory').innerHTML=g.bag.map(i=>`<button class="weapon-item ${!WEAPONS[i.kind].base?'special':''} ${materials.includes(i.id)?'selected':''}" data-item="${i.id}" aria-pressed="${materials.includes(i.id)}" aria-label="${WEAPONS[i.kind].name}, ${HEROES[WEAPONS[i.kind].role].name} 전용, ${WEAPONS[i.kind].desc}">${weaponArt(i.kind)}<span>${WEAPONS[i.kind].name}</span>${materials.includes(i.id)?`<span class="selection-number">${materials.indexOf(i.id)+1}</span>`:''}</button>`).join('')+Array.from({length:Math.max(0,4-g.bag.length)},()=>'<span class="empty-item" aria-hidden="true">+</span>').join('');
const item=mi.length===1?mi[0]:null,compatible=item&&WEAPONS[item.kind].role===u.type;$('#equip-area').innerHTML=item?`<p class="equip-info">${WEAPONS[item.kind].name} · 공격 힘 ${WEAPONS[item.kind].power}<br>${WEAPONS[item.kind].desc}</p><button class="equip-button" id="equip" ${!edit||!compatible?'disabled':''}>${compatible?`${HEROES[u.type].name}에게 장착하기`:`${HEROES[WEAPONS[item.kind].role].name}를 먼저 골라 주세요`}</button>`:'<p class="equip-info">무기 하나는 장착, 두 개는 합성!<br>장착했던 무기는 가방으로 돌아와요.</p>';
$('#weapon-shop').innerHTML=['sword','hammer','bow','staff'].map(k=>`<button class="buy-weapon" data-buy-weapon="${k}" ${!edit||g.coins<20||g.bag.length>=20?'disabled':''} aria-label="${WEAPONS[k].name} 구매 20 코인">${weaponArt(k)}<span>${WEAPONS[k].name}</span><b>${icon('coin')}20</b></button>`).join('');
const tips=[['먼저 레인저를 모집하세요','팀에서 레인저를 모집하면 기본 무기도 함께 받아요.'],['나무검 + 별지팡이 → 불꽃검','무기 가방의 나무검 + 별지팡이를 고르고 합성해요.'],['완성한 무기를 장착하세요','가디언을 고른 뒤 불꽃검 하나를 선택하고 장착해요.'],['준비 완료 · 전투를 시작하세요','전투 시작을 누르면 친구들이 자동으로 싸워요.']];$('#tutorial').hidden=g.tutorial>=4||!edit;if(g.tutorial<4){$('#tutorial-title').textContent=tips[g.tutorial][0];$('#tutorial-text').textContent=tips[g.tutorial][1];$('.tutorial-number').textContent=g.tutorial+1;}$('.forge-note').innerHTML=icon('check')+(!edit?'전투가 끝나면 공방을 다시 이용할 수 있어요.':g.bag.length>=20?'가방이 가득해요. 합성해서 자리를 만들어요.':g.coins<20?'기본 무기 구매에는 코인 20개가 필요해요.':'합성은 언제나 성공! 실패 걱정 없어요.');updateBattleHUD();if(focusKey&&!focused.isConnected){const target=$(focusKey);if(target&&!target.disabled)target.focus({preventScroll:true});}}
function updateBattleHUD(){$('#coins').textContent=g.coins;$('#crystal').value=g.crystal;$('#crystal-label').textContent=g.crystal;$('#map-status').textContent=g.phase==='prep'?(moveMode?'이동할 자리를 눌러 주세요 · 친구끼리 교환도 가능!':'친구를 누르면 장착할 대상을 고를 수 있어요'):g.phase==='paused'?'천천히 생각해도 괜찮아요':g.phase==='battle'?`처치 ${g.run.kills} / ${WAVES[g.wave-1].types.length} · 얻은 코인 +${g.run.earned}`:g.phase==='lost'?'친구들이 잠깐 쉬어 가요':'우리 팀, 정말 멋졌어요!';}
$('#forge-targets').addEventListener('click',e=>{const b=e.target.closest('[data-equip-unit]');if(b){selected=Number(b.dataset.equipUnit);moveMode=false;renderUI();}});
$('#tutorial-action').onclick=()=>showScreen(g.tutorial===0?'team':g.tutorial<3?'forge':'battle');
$('#hero-shop').addEventListener('click',e=>{const b=e.target.closest('[data-buy-hero]');if(!b)return;const r=buyHero(g,b.dataset.buyHero);if(r.ok)selected=r.id;action(r);});
$('#weapon-shop').addEventListener('click',e=>{const b=e.target.closest('[data-buy-weapon]');if(b)action(buyWeapon(g,b.dataset.buyWeapon));});
$('#inventory').addEventListener('click',e=>{const b=e.target.closest('[data-item]');if(!b)return;const id=Number(b.dataset.item);if(materials.includes(id))materials=materials.filter(i=>i!==id);else materials=materials.length>=2?[id]:[...materials,id];renderUI();});
$('#clear-selection').onclick=()=>{materials=[];renderUI();};
$('#craft').onclick=()=>{const r=mix(g,materials);if(r.ok){materials=[r.id];const hero=g.units.find(u=>u.type===WEAPONS[r.kind].role);if(hero)selected=hero.id;$('.forge').classList.remove('crafted');void $('.forge').offsetWidth;$('.forge').classList.add('crafted');}action(r,'craft');};
$('#equip-area').addEventListener('click',e=>{if(!e.target.closest('#equip'))return;const r=equip(g,selected,materials[0]);if(r.ok)materials=[];action(r,'craft');});
$('#roster').addEventListener('click',e=>{const b=e.target.closest('[data-unit]');if(b){selected=Number(b.dataset.unit);moveMode=false;renderUI();}});
$('#slot-controls').addEventListener('click',e=>{const b=e.target.closest('[data-slot]');if(!b||!canEdit(g))return;const slot=Number(b.dataset.slot),u=g.units.find(u=>u.slot===slot);if(moveMode||!u){moveMode=false;action(moveHero(g,selected,slot),'tap');}else{selected=u.id;renderUI();}});
$('#hero-detail').addEventListener('click',e=>{if(e.target.closest('#move-hero')){moveMode=!moveMode;renderUI();if(moveMode){showScreen('battle',false);$('.battle-card').scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});toast('전장에서 이동할 자리를 눌러 주세요.');}}});
function mainAction(){showScreen('battle',false);if(g.phase==='prep'){moveMode=false;action(start(g),'tap');if(innerWidth<821)$('.battle-card').scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});}else if(['battle','paused'].includes(g.phase)){pause(g);persist();renderUI();}else if(g.phase==='reward'){nextWave(g);materials=[];persist();renderUI();}else if(g.phase==='lost'){retry(g);materials=[];persist();renderUI();}else showResult();}
$('#start').onclick=mainAction;$('#speed').onclick=()=>{g.speed=g.speed===1?2:1;persist();renderUI();};$('#sound').onclick=()=>{g.muted=!g.muted;persist();renderUI();sound('coin');};
function openDialog(id){if(g.phase==='battle'){pause(g);renderUI();}$(id).showModal();}
$('#help').onclick=()=>openDialog('#help-dialog');$('#recipes').onclick=()=>openDialog('#recipe-dialog');$('#restart').onclick=()=>openDialog('#restart-dialog');
$$('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('#confirm-restart').onclick=()=>{const muted=g.muted;g=fresh();g.muted=muted;selected=g.units[0].id;materials=[];lastPhase='prep';showScreen('battle');$$('dialog[open]').forEach(d=>d.close());persist();renderUI();toast('새로운 모험이 시작됐어요!');};
$('#recipe-list').innerHTML=RECIPES.filter(r=>r[0]!==r[1]).map(([a,b,k])=>`<div class="recipe-row"><div class="recipe-icons">${weaponArt(a)}<span>+</span>${weaponArt(b)}<span>→</span>${weaponArt(k)}</div><div><h3>${WEAPONS[k].name} · ${HEROES[WEAPONS[k].role].name}</h3><p>${WEAPONS[k].desc}</p></div></div>`).join('');
function showResult(){showScreen('battle');const lost=g.phase==='lost',won=g.phase==='won';$('#result-art').innerHTML=lost?heroArt('melee'):`${heroArt('melee')}<span>${won?'♛':'✧'}</span>${heroArt('ranged')}`;$('#result-eyebrow').textContent=lost?'TAKE A BREATH, TRY AGAIN':won?'YOU ARE OUR FOREST HEROES':'A LITTLE VICTORY, A BIG SMILE';$('#result-title').textContent=lost?'괜찮아, 다시 해 보자!':won?'방어 작전 완료!':`${g.wave}번째 전투 승리!`;$('#result-description').textContent=lost?'코인과 무기는 전투 직전으로 돌아가요. 친구를 더 부르거나 무기를 바꿔 보세요.':won?'골렘 왕까지 물리쳤어요. 친구들과 만든 멋진 팀, 정말 든든했어요!':'친구들의 체력과 보석이 다음 전투 전에 회복돼요. 새 코인으로 더 멋진 팀을 만들어 보세요.';$('#result-stats').innerHTML=lost?'<div class="result-stat"><strong>그대로</strong><span>코인 · 무기 · 친구 복구</span></div>':`<div class="result-stat"><strong>+${g.run?.earned??0}</strong><span>전투 코인</span></div><div class="result-stat"><strong>+${g.run?.reward??0}</strong><span>승리 보너스</span></div><div class="result-stat"><strong>${g.crystal}</strong><span>보석 체력</span></div>`;$('#result-action').textContent=lost?'다시 준비하기':won?'우리 팀 구경하기':'다음 모험 준비하기';if(!$('#result-dialog').open)$('#result-dialog').showModal();}
$('#result-action').onclick=()=>{$('#result-dialog').close();if(g.phase==='lost')retry(g);else if(g.phase==='reward')nextWave(g);materials=[];persist();renderUI();};
document.addEventListener('keydown',e=>{if(e.code==='Space'&&!e.repeat&&!document.querySelector('dialog[open]')&&!['BUTTON','A','INPUT'].includes(e.target.tagName)){e.preventDefault();mainAction();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&g.phase==='battle'){pause(g);persist();renderUI();}});
window.addEventListener('pagehide',persist);
function frame(now){const dt=previous?Math.min((now-previous)/1000,.1):0;previous=now;step(g,dt);if(g.phase!==lastPhase){lastPhase=g.phase;if(['reward','won','lost'].includes(g.phase)){persist();renderUI();showResult();sound(g.phase==='lost'?'lost':'win');}}if(g.run?.events?.length){const events=g.run.events.splice(0);if(events.includes('pop'))sound('pop');}acc+=dt;if(acc>.2){acc=0;updateBattleHUD();}renderer?.draw(g,selected,now,reduced);requestAnimationFrame(frame);}
renderUI();persist();try{renderer=await makeRenderer($('#world'));renderer.draw(g,selected,performance.now(),reduced);$('#loading').hidden=true;requestAnimationFrame(frame);if(['reward','won'].includes(g.phase))showResult();}catch(e){$('#loading').textContent='그림을 불러오지 못했어요. 새로고침해 주세요.';console.error(e);}
