import assert from 'node:assert/strict';
const {chromium}=await import(process.env.PLAYWRIGHT_MODULE||'playwright');
const BASE=process.env.MIX_URL||'http://127.0.0.1:8770/mix-heroes/';const KEY='junwoo-mix-heroes-v1';
const browser=await chromium.launch({channel:'chrome',headless:true});const errors=[];let finalPrep;
async function pageFor(mobile=false){const ctx=await browser.newContext({viewport:mobile?{width:390,height:844}:{width:1440,height:1050},isMobile:mobile,hasTouch:mobile,deviceScaleFactor:1,reducedMotion:'reduce'});const p=await ctx.newPage();p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.url()+' '+r.status());});await p.clock.install({time:new Date('2026-10-03T12:00:00Z')});await p.clock.pauseAt(new Date('2026-10-03T12:00:01Z'));await p.goto(BASE);await p.locator('#loading').waitFor({state:'hidden'});return p;}
async function state(p){return p.evaluate(k=>JSON.parse(localStorage.getItem(k)),KEY);}
async function click(p,selector,mobile=false){if(mobile){const screen=/data-buy-hero|data-unit|#move-hero/.test(selector)?'team':/data-buy-weapon|data-item|data-equip-unit|#clear-selection|#craft|#equip|#recipes/.test(selector)?'forge':/data-slot|#start/.test(selector)?'battle':null;if(screen&&await p.locator('body').getAttribute('data-screen')!==screen)await p.locator(`.quick-nav [data-screen="${screen}"]`).tap();}const el=p.locator(selector);if(mobile)await el.tap();else await el.click();}
async function arm(p,u,target,a,b,mobile=false){let g=await state(p);if(u.weapon===target)return;for(const k of [a,b]){const need=a===b?2:1;while(g.bag.filter(i=>i.kind===k).length<need&&g.coins>=20){await click(p,`[data-buy-weapon="${k}"]`,mobile);g=await state(p);}}const aa=g.bag.find(i=>i.kind===a),bb=g.bag.find(i=>i.kind===b&&i.id!==aa?.id);if(!aa||!bb)return;await click(p,'#clear-selection',mobile);await click(p,`[data-item="${aa.id}"]`,mobile);await click(p,`[data-item="${bb.id}"]`,mobile);assert.equal(await p.locator('#craft').isEnabled(),true);await click(p,'#craft',mobile);await click(p,`[data-equip-unit="${u.id}"]`,mobile);await click(p,'#equip',mobile);g=await state(p);assert.equal(g.units.find(x=>x.id===u.id).weapon,target);}
async function prepare(p,mobile=false){let g=await state(p);if(g.wave===1){await click(p,'[data-buy-hero="ranged"]',mobile);await click(p,'[data-item="2"]',mobile);await click(p,'[data-item="3"]',mobile);assert.match(await p.locator('#mix-info').textContent(),/불꽃검/);await click(p,'#craft',mobile);await click(p,'#equip',mobile);g=await state(p);assert.equal(g.units[0].weapon,'fire');assert.equal(g.bag[0].kind,'sword');}
while(g.units.length<Math.min(6,g.wave+1)){const type=g.units.length%2===0?'melee':'ranged';if(g.coins<(type==='melee'?50:60))break;await click(p,`[data-buy-hero="${type}"]`,mobile);g=await state(p);}for(let i=0;i<g.units.length;i++){const u=g.units[i];if(!['sword','bow','hammer','staff'].includes(u.weapon))continue;if(u.type==='melee')await arm(p,u,i%3===0?'fire':'thunder',i%3===0?'sword':'hammer','staff',mobile);else await arm(p,u,i%3===0?'wind':'ice',i%3===0?'sword':'bow',i%3===0?'bow':'staff',mobile);} }
async function fight(p,mobile=false){await click(p,'#start',mobile);for(let i=0;i<40;i++){await p.clock.runFor(5000);const phase=await p.locator('body').getAttribute('data-phase');if(phase!=='battle'){assert.ok(['reward','won'].includes(phase),`unexpected phase ${phase}`);assert.equal(await p.locator('#result-dialog').isVisible(),true);return;}}throw Error('combat never completed');}
try{const p=await pageFor();await p.evaluate(()=>localStorage.setItem('our-little-rescue-v1','existing-rescue-save'));await p.screenshot({path:'/tmp/mix-desktop-final.png',fullPage:true});
await prepare(p);const before=await state(p);
await click(p,'[data-unit="1"]');await click(p,'#move-hero');await click(p,'[data-slot="3"]');assert.equal((await state(p)).units[0].slot,3);await click(p,'#move-hero');await click(p,'[data-slot="4"]');
await click(p,'#start');await p.clock.runFor(6000);await click(p,'#start');assert.equal(await p.locator('body').getAttribute('data-phase'),'paused');const status=await p.locator('#map-status').textContent();await p.clock.runFor(3000);assert.equal(await p.locator('#map-status').textContent(),status);assert.equal((await state(p)).coins,before.coins);
await p.reload();await p.locator('#loading').waitFor({state:'hidden'});assert.equal(await p.locator('body').getAttribute('data-phase'),'prep');assert.equal((await state(p)).coins,before.coins);console.log('PASS purchase, mix, equip, move, pause, checkpoint reload');
await fight(p);assert.equal(await p.evaluate(()=>localStorage.getItem('our-little-rescue-v1')),'existing-rescue-save');console.log('PASS desktop wave 1');await click(p,'#result-action');
for(let wave=2;wave<=10;wave++){await prepare(p);if(wave===10){finalPrep=await state(p);await click(p,'#start');await p.clock.runFor(14000);await p.screenshot({path:'/tmp/mix-boss-battle.png',fullPage:true});for(let i=0;i<35&&(await p.locator('body').getAttribute('data-phase'))==='battle';i++)await p.clock.runFor(5000);assert.equal(await p.locator('body').getAttribute('data-phase'),'won');}else await fight(p);console.log('PASS desktop wave',wave);if(wave<10)await click(p,'#result-action');}
await p.screenshot({path:'/tmp/mix-victory.png',fullPage:true});const money=(await state(p)).coins;await p.reload();await p.locator('#loading').waitFor({state:'hidden'});assert.equal((await state(p)).coins,money);assert.equal(await p.locator('#result-dialog').isVisible(),true);await click(p,'#result-action');await click(p,'#recipes');assert.equal(await p.locator('.recipe-row').count(),4);await p.locator('#recipe-dialog [data-close]').last().click();console.log('PASS victory reload without duplicate rewards and recipe book');
const m=await pageFor(true);assert.equal(await m.locator('#battle-area').isVisible(),true);assert.equal(await m.locator('#team-area').isVisible(),false);assert.equal(await m.locator('#forge-area').isVisible(),false);assert.ok((await m.locator('#start').boundingBox()).y<760);await m.locator('.quick-nav [data-screen="team"]').tap();assert.equal(await m.locator('#team-area').isVisible(),true);assert.equal(await m.locator('#battle-area').isVisible(),false);await m.locator('.quick-nav [data-screen="forge"]').tap();assert.equal(await m.locator('#forge-area').isVisible(),true);assert.equal(await m.locator('#team-area').isVisible(),false);await m.locator('.quick-nav [data-screen="battle"]').tap();console.log('PASS three mobile tabs, one active panel, start above bottom navigation');await m.screenshot({path:'/tmp/mix-mobile-final.png',fullPage:true});await prepare(m,true);await fight(m,true);console.log('PASS touch purchase, mixing, equipment and first wave');await click(m,'#result-action',true);await m.addInitScript(({key,data})=>localStorage.setItem(key,JSON.stringify(data)),{key:KEY,data:finalPrep});await m.reload();await m.locator('#loading').waitFor({state:'hidden'});assert.equal((await state(m)).wave,10);await fight(m,true);assert.equal(await m.locator('body').getAttribute('data-phase'),'won');console.log('PASS touch final boss');await click(m,'#result-action',true);
for(const width of [320,390,768]){await m.setViewportSize({width,height:844});for(const screen of ['battle','team','forge']){await m.locator(`.quick-nav [data-screen="${screen}"]`).tap();assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'horizontal overflow '+width+' '+screen);}}
await m.setViewportSize({width:390,height:844});await click(m,'#restart',true);await click(m,'#confirm-restart',true);assert.equal((await state(m)).wave,1);assert.equal((await state(m)).coins,145);await click(m,'#help',true);await m.locator('#help-dialog [data-close]').last().tap();console.log('PASS mobile layouts, help, fresh adventure');
const corrupt=await pageFor();await corrupt.addInitScript(k=>localStorage.setItem(k,'broken-json'),KEY);await corrupt.reload();await corrupt.locator('#loading').waitFor({state:'hidden'});assert.equal((await state(corrupt)).coins,145);
const blocked=await browser.newContext();await blocked.addInitScript(()=>{Storage.prototype.setItem=()=>{throw new Error('storage blocked')};Storage.prototype.getItem=()=>{throw new Error('storage blocked')};});const bp=await blocked.newPage();await bp.goto(BASE);await bp.locator('#loading').waitFor({state:'hidden'});await bp.locator('[data-buy-hero="ranged"]').click();assert.equal(await bp.locator('#coins').textContent(),'85');assert.match(await bp.locator('#save-status').textContent(),/저장이 제한/);console.log('PASS corrupt and unavailable storage');assert.deepEqual(errors,[]);console.log('PASS no browser errors or missing assets');}finally{await browser.close();}
