import test from 'node:test';import assert from 'node:assert/strict';
import {fresh,buyHero,buyWeapon,moveHero,mix,equip,start,step,pause,retry,nextWave,serialize,restore,campaign} from '../engine.mjs';
import {WEAPONS,RECIPES,HEROES,ENEMIES,clone} from '../data.mjs';
import {prepare,runWave} from './balance.mjs';
for(const strategy of ['mixed','same'])for(const speed of [1,2])test(`10-wave campaign: ${strategy}, speed ${speed}`,()=>{const g=fresh();g.speed=speed;for(let w=1;w<=10;w++){prepare(g,strategy);const t=runWave(g);assert.ok(t<180,`wave ${w} must finish`);assert.equal(g.phase,w===10?'won':'reward');assert.ok(g.crystal>0);const money=g.coins;const saved=restore(serialize(g));assert.equal(saved.coins,money);assert.equal(saved.phase,g.phase);if(w<10){assert.equal(nextWave(g),true);assert.equal(g.crystal,100);assert.equal(nextWave(g),false);assert.equal(g.coins,money);}}});
test('buying spends exact coins, places by role, includes compatible equipment; rejects overspend/full team',()=>{const g=fresh();assert.equal(buyHero(g,'ranged').ok,true);assert.equal(g.coins,85);assert.equal(g.units[1].slot,1);assert.equal(g.units[1].weapon,'bow');buyHero(g,'melee');assert.equal(g.coins,35);const before=campaign(g);assert.equal(buyHero(g,'ranged').ok,false);assert.deepEqual(campaign(g),before);g.coins=500;while(g.units.length<6)buyHero(g,'melee');assert.equal(new Set(g.units.map(u=>u.slot)).size,6);assert.equal(buyHero(g,'ranged').ok,false);assert.equal(buyHero(g,'unknown').ok,false);});
for(const [a,b,k]of RECIPES)test(`recipe ${a} + ${b} = ${k}; preview-safe, atomic consumption`,()=>{const g=fresh();g.bag=[{id:2,kind:a},{id:3,kind:b}];const coins=g.coins;const r=mix(g,[2,3]);assert.equal(r.kind,k);assert.equal(g.bag.length,1);assert.equal(g.coins,coins);assert.equal(g.bag[0].kind,k);assert.equal(mix(g,[2,3]).ok,false);});
test('invalid, duplicate and completed weapons cannot be mixed; no resources lost',()=>{const g=fresh();const saved=serialize(g);assert.equal(mix(g,[2,2]).ok,false);assert.equal(mix(g,[2,900]).ok,false);assert.equal(serialize(g),saved);g.bag[0].kind='hammer';g.bag[1].kind='bow';assert.equal(mix(g,[2,3]).ok,false);g.bag[0].kind='fire';g.bag[1].kind='fire';assert.equal(mix(g,[2,3]).ok,false);});
test('equipping checks role and returns old weapon, no creation or loss',()=>{const g=fresh();const old=serialize(g);assert.equal(equip(g,1,3).ok,false);assert.equal(serialize(g),old);const r=mix(g,[2,3]);assert.equal(equip(g,1,r.id).ok,true);assert.equal(g.units[0].weapon,'fire');assert.equal(g.bag[0].kind,'sword');assert.equal(g.units.length+g.bag.length,2);});
test('moving swaps occupied slots, and invalid moves preserve placement',()=>{const g=fresh();buyHero(g,'ranged');moveHero(g,1,1);assert.equal(g.units[0].slot,1);assert.equal(g.units[1].slot,4);assert.equal(moveHero(g,1,9).ok,false);assert.equal(new Set(g.units.map(u=>u.slot)).size,2);});
test('battle locks economy, pause freezes all state, units have different range',()=>{const g=fresh();start(g);const before=serialize(g);assert.equal(buyHero(g,'melee').ok,false);assert.equal(buyWeapon(g,'sword').ok,false);assert.equal(mix(g,[2,3]).ok,false);assert.equal(equip(g,1,2).ok,false);assert.equal(moveHero(g,1,1).ok,false);assert.equal(serialize(g),before);pause(g);const snap=clone(g);step(g,1);assert.deepEqual(g,snap);assert.ok(HEROES.ranged.range>HEROES.melee.range*2);pause(g);step(g,.1);assert.ok(g.run.time>0);});
test('loss, reload and retry restore exact pre-battle economy and army',()=>{const g=fresh();buyHero(g,'ranged');const pre=campaign(g);start(g);g.coins+=99;g.crystal=0;step(g,.1);assert.equal(g.phase,'lost');const restored=restore(serialize(g));assert.deepEqual(campaign(restored),pre);assert.equal(retry(g),true);assert.deepEqual(campaign(g),pre);assert.equal(retry(g),false);});
test('no infinite battle when all defenders fall; enemies reach and damage the crystal',()=>{const g=fresh();g.wave=10;start(g);for(const u of g.run.units)u.hp=0;for(let i=0;i<2200&&g.phase==='battle';i++)step(g,.1);assert.equal(g.phase,'lost');assert.equal(g.crystal,0);});
test('basic equipment alone is insufficient for final boss; improved gear matters',()=>{const g=fresh();g.coins=1000;g.wave=10;while(g.units.length<6)buyHero(g,g.units.length%2?'ranged':'melee');runWave(g);assert.equal(g.phase,'lost');});
function combat(weapon,type='melee'){const g=fresh();g.units[0].weapon=weapon;g.units[0].type=type;start(g);g.run.spawned=999;g.run.spawnIn=999;g.run.units[0].x=380;g.run.units[0].y=330;g.run.units[0].cd=0;g.run.enemies=[enemy(1,435,330),enemy(2,465,330)];return g;}
function enemy(id,x,y){return {id,type:'tank',x,y,hp:1000,maxHp:1000,cd:999,burn:0,slow:0,flash:0,anim:0};}
test('fire applies a timed burn with damage after the first hit',()=>{const g=combat('fire');step(g,.01);const e=g.run.enemies[0];assert.ok(e.burn>0);const hp=e.hp;g.run.units[0].cd=10;for(let i=0;i<6;i++)step(g,.1);assert.ok(e.hp<hp);assert.ok(g.run.fx.length<20);});
test('thunder damages nearby enemies, normal swords do not',()=>{const g=combat('thunder');step(g,.01);assert.ok(g.run.enemies[1].hp<1000);const s=combat('sword');step(s,.01);assert.equal(s.run.enemies[1].hp,1000);});
test('ice projectiles slow their target, projectiles take time to arrive',()=>{const g=combat('ice','ranged');step(g,.01);assert.equal(g.run.enemies[0].slow,0);assert.equal(g.run.shots.length,1);for(let i=0;i<7;i++)step(g,.05);assert.ok(g.run.enemies[0].slow>0);});
test('wind projectile pierces a second enemy, does not hit a third',()=>{const g=combat('wind','ranged');g.run.enemies.push(enemy(3,495,330));step(g,.01);g.run.units[0].cd=99;for(let i=0;i<12;i++)step(g,.05);assert.ok(g.run.enemies[0].hp<1000);assert.ok(g.run.enemies[1].hp<1000);assert.equal(g.run.enemies[2].hp,1000);});
test('corrupt and impossible saved state resets safely; valid progress survives',()=>{for(const raw of ['null','bad','{}',JSON.stringify({...fresh(),coins:-1}),JSON.stringify({...fresh(),units:[]}),JSON.stringify({...fresh(),phase:'battle'}),JSON.stringify({...fresh(),nextId:1}),JSON.stringify({...fresh(),bag:[{id:2,kind:'bad'}]})])assert.deepEqual(restore(raw),fresh());const g=fresh();buyHero(g,'ranged');assert.equal(restore(serialize(g)).units.length,2);});
test('weapon bag limit and shop constraints never consume coins on failure',()=>{const g=fresh();g.coins=1000;while(g.bag.length<20)buyWeapon(g,'sword');const money=g.coins;assert.equal(buyWeapon(g,'sword').ok,false);assert.equal(buyWeapon(g,'fire').ok,false);assert.equal(g.coins,money);});
